package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

type EMRInstanceFleetConfig struct {
	Type       string                           `yaml:"Type"`
	Properties EMRInstanceFleetConfigProperties `yaml:"Properties"`
	Condition  interface{}                      `yaml:"Condition,omitempty"`
	Metadata   interface{}                      `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                      `yaml:"DependsOn,omitempty"`
}

type EMRInstanceFleetConfigProperties struct {
	ClusterId              interface{}                                                             `yaml:"ClusterId"`
	InstanceFleetType      interface{}                                                             `yaml:"InstanceFleetType"`
	Name                   interface{}                                                             `yaml:"Name,omitempty"`
	TargetOnDemandCapacity interface{}                                                             `yaml:"TargetOnDemandCapacity,omitempty"`
	TargetSpotCapacity     interface{}                                                             `yaml:"TargetSpotCapacity,omitempty"`
	InstanceTypeConfigs    interface{}                                                             `yaml:"InstanceTypeConfigs,omitempty"`
	LaunchSpecifications   *properties.InstanceFleetConfig_InstanceFleetProvisioningSpecifications `yaml:"LaunchSpecifications,omitempty"`
}

func NewEMRInstanceFleetConfig(properties EMRInstanceFleetConfigProperties, deps ...interface{}) EMRInstanceFleetConfig {
	return EMRInstanceFleetConfig{
		Type:       "AWS::EMR::InstanceFleetConfig",
		Properties: properties,
		DependsOn:  deps,
	}
}

func ParseEMRInstanceFleetConfig(ctx map[string]interface{}, name string, data string) (cf types.TemplateObject, err error) {
	var resource EMRInstanceFleetConfig
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: EMRInstanceFleetConfig - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

func (resource EMRInstanceFleetConfig) Validate() []error {
	return resource.Properties.Validate()
}

func (resource EMRInstanceFleetConfigProperties) Validate() []error {
	errs := []error{}
	if resource.ClusterId == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'ClusterId'"))
	}
	if resource.InstanceFleetType == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'InstanceFleetType'"))
	}
	return errs
}
