language: go

os:
- linux

go:
- 1.10.1

sudo: required
env:
  matrix:
  - DEP_VERSION="0.4.1"
  global:
    secure: wWW0QLPr3+jPP8gtRX12FdlMbhfsyfnTXx3aboCVIYKFd1p0+ng4jo4N5fNCLBBpK6JgH+NtTqvsXdGBFDoVHF5jo3qsxYneonh0eC9ffXD/Rbbp4CeHqBZKVOTyzxMvLM1HWzI4Ynq8VP5ktPx+O4enuXTUlZQ7NOtg4yplliEXIIueu/QNIxOd0lDLwy2k/lHjcWPHAKxEV0BAnRxSA4fe7I/1q3VQctGjVVS94HCsE5C3ecCzf3rAsxppyaNK1SoFmIWNDT5PDlBBONM1pzKEiDsZEIFLIBYfM0RCkEhXwwskFTPxRgN7/g8BIv/qD59MVc1/ywSsx+fFPUZRHH+zykFiD1aNKA2D9RP0sRYuaqCpxwq/+ZD6hh4t3bRfZ1tZq94FiSMHTfHaUFOvpHKSJf3lkpo8nGPw8exFkEi0mgeKyvFgN4Vj42bVsZklksZROwJuNMNUWLBNAr3dlZCZyGbh26CUFnq0izsI9HK1hQQDGRxeEBD+WTIvyAYEXdBzIHU+bnB1E7Mg7yuhYrLybRDIidypRSVieJ4WkAj766ILs4G/jHoVzw1RjH1qFHsycZellY52wVjd8BVSqhQDNTLivIMDOGA/UjXLEoKnvMu1pR3lzSQLHEcDPXfB8N+nZn3XoAVhFP7rxXdoafL6bjJJrzDeJvxGNJWZgYQ=

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
- dep ensure
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go generate
- go test -v -covermode=count -coverprofile=coverage.out ./....
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"

before_deploy:
- go get github.com/karalabe/xgo
- "./build/ci/build.sh"

deploy:
  provider: releases
  api_key:
    secure: RG9Hd77NoFS7NwMjDVyurbROV33bsefz8kW7XigfFDURTSfGAsMjyWR3wWt4qWCgCw2gMtszLlYp8yoX0xlHV38UslDscEKfvUnzWdHDPPgM2AtRyLFk5tYeOaX+t0VQDZA3KKgQRUitPgzC8SoaVdwQL5EhkvYKM4pUM2irvFYLT/pRIaP1yJ6gsrJqiybjpfpUHwH6VtgSLKjj6o6YBywr7LHSlrAGK2N+0eSncs5C0A0F+Jfs4NPPB0v2ke8SvHprN3V9pC51KZTWTuApKu+bAXxQbnZo4aOFdK52f7tO2uKj7xFbcCgpj8HDrypofX3HwzyAYV6Xd23vdhbHisJDkqwQpUW/hx/bWygGk/4b92D+yw9fMVgec/Lg03+evXkXJZ0ZsRSuANrKtsgVk8+8RsH/eGgsMAK7eISESxVkAW8C2CIPjvRP6E5F7I6fW8v7nj1SJZablCCNRAD20E3ICkXkhJTADWHcxEr2Bnl/m4RJNUsrO5OJeY1E2zbWJwwqIRGK5O0NtaTfRvcPgI2iJ9dmenJFUttYm1631C5MIFKFCISBrIBdTIiOVZa5xWKek18ReKblrT6ARyg1yxk5b7PvAbnmp+jfYvj9d9hYaKYmbASGC2m9Qa7M+mpCbrElrZ9EB6KD98lJUXjAZXpcmGBWnxXpglxBSM2O1gg=
  file_glob: true
  file: ".build/*"
  skip_cleanup: true
  on:
    tags: true
