package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// AliasVersionWeight Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-alias-versionweight.html
type AliasVersionWeight struct {
	FunctionVersion interface{} `yaml:"FunctionVersion"`
	FunctionWeight  interface{} `yaml:"FunctionWeight"`
}

// AliasVersionWeight validation
func (resource AliasVersionWeight) Validate() []error {
	errs := []error{}

	if resource.FunctionVersion == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'FunctionVersion'"))
	}
	if resource.FunctionWeight == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'FunctionWeight'"))
	}
	return errs
}
