package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// ApplicationReferenceDataSourceS3ReferenceDataSource Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalytics-applicationreferencedatasource-s3referencedatasource.html
type ApplicationReferenceDataSourceS3ReferenceDataSource struct {
	BucketARN        interface{} `yaml:"BucketARN"`
	FileKey          interface{} `yaml:"FileKey"`
	ReferenceRoleARN interface{} `yaml:"ReferenceRoleARN"`
}

// ApplicationReferenceDataSourceS3ReferenceDataSource validation
func (resource ApplicationReferenceDataSourceS3ReferenceDataSource) Validate() []error {
	errors := []error{}

	return errors
}
