package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ApplicationInput Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalytics-application-input.html
type ApplicationInput struct {
	NamePrefix                   interface{} `yaml:"NamePrefix"`
	KinesisStreamsInput          interface{} `yaml:"KinesisStreamsInput,omitempty"`
	KinesisFirehoseInput         interface{} `yaml:"KinesisFirehoseInput,omitempty"`
	InputSchema                  interface{} `yaml:"InputSchema"`
	InputProcessingConfiguration interface{} `yaml:"InputProcessingConfiguration,omitempty"`
	InputParallelism             interface{} `yaml:"InputParallelism,omitempty"`
}

// ApplicationInput validation
func (resource ApplicationInput) Validate() []error {
	errors := []error{}

	return errors
}
