package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ApplicationOutputKinesisFirehoseOutput Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalytics-applicationoutput-kinesisfirehoseoutput.html
type ApplicationOutputKinesisFirehoseOutput struct {
	ResourceARN interface{} `yaml:"ResourceARN"`
	RoleARN     interface{} `yaml:"RoleARN"`
}

// ApplicationOutputKinesisFirehoseOutput validation
func (resource ApplicationOutputKinesisFirehoseOutput) Validate() []error {
	errors := []error{}

	if resource.ResourceARN == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ResourceARN'"))
	}
	if resource.RoleARN == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'RoleARN'"))
	}
	return errors
}
