package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ApplicationKinesisStreamsInput Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalytics-application-kinesisstreamsinput.html
type ApplicationKinesisStreamsInput struct {
	ResourceARN interface{} `yaml:"ResourceARN"`
	RoleARN     interface{} `yaml:"RoleARN"`
}

// ApplicationKinesisStreamsInput validation
func (resource ApplicationKinesisStreamsInput) Validate() []error {
	errors := []error{}

	return errors
}
