package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// AssociationInstanceAssociationOutputLocation Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ssm-association-instanceassociationoutputlocation.html
type AssociationInstanceAssociationOutputLocation struct {
	S3Location *AssociationS3OutputLocation `yaml:"S3Location,omitempty"`
}

// AssociationInstanceAssociationOutputLocation validation
func (resource AssociationInstanceAssociationOutputLocation) Validate() []error {
	errors := []error{}

	return errors
}
