package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// AutoScalingGroupMixedInstancesPolicy Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-as-group-mixedinstancespolicy.html
type AutoScalingGroupMixedInstancesPolicy struct {
	LaunchTemplate        interface{} `yaml:"LaunchTemplate"`
	InstancesDistribution interface{} `yaml:"InstancesDistribution,omitempty"`
}

// AutoScalingGroupMixedInstancesPolicy validation
func (resource AutoScalingGroupMixedInstancesPolicy) Validate() []error {
	errors := []error{}

	return errors
}
