package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// BucketTagFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-tagfilter.html
type BucketTagFilter struct {
	Key   interface{} `yaml:"Key"`
	Value interface{} `yaml:"Value"`
}

// BucketTagFilter validation
func (resource BucketTagFilter) Validate() []error {
	errors := []error{}

	return errors
}
