package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// BucketServerSideEncryptionRule Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html
type BucketServerSideEncryptionRule struct {
	ServerSideEncryptionByDefault *BucketServerSideEncryptionByDefault `yaml:"ServerSideEncryptionByDefault,omitempty"`
}

// BucketServerSideEncryptionRule validation
func (resource BucketServerSideEncryptionRule) Validate() []error {
	errs := []error{}

	return errs
}
