package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// BucketNotificationFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfiguration-config-filter.html
type BucketNotificationFilter struct {
	S3Key *BucketS3KeyFilter `yaml:"S3Key"`
}

// BucketNotificationFilter validation
func (resource BucketNotificationFilter) Validate() []error {
	errors := []error{}

	if resource.S3Key == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'S3Key'"))
	} else {
		errors = append(errors, resource.S3Key.Validate()...)
	}
	return errors
}
