package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// BucketServerSideEncryptionRule Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html
type BucketServerSideEncryptionRule struct {
	ServerSideEncryptionByDefault *BucketServerSideEncryptionByDefault `yaml:"ServerSideEncryptionByDefault,omitempty"`
}

// BucketServerSideEncryptionRule validation
func (resource BucketServerSideEncryptionRule) Validate() []error {
	errors := []error{}

	return errors
}
