package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// BucketRedirectRule Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-websiteconfiguration-routingrules-redirectrule.html
type BucketRedirectRule struct {
	HostName             interface{} `yaml:"HostName,omitempty"`
	HttpRedirectCode     interface{} `yaml:"HttpRedirectCode,omitempty"`
	Protocol             interface{} `yaml:"Protocol,omitempty"`
	ReplaceKeyPrefixWith interface{} `yaml:"ReplaceKeyPrefixWith,omitempty"`
	ReplaceKeyWith       interface{} `yaml:"ReplaceKeyWith,omitempty"`
}

// BucketRedirectRule validation
func (resource BucketRedirectRule) Validate() []error {
	errors := []error{}

	return errors
}
