package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// BucketS3KeyFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfiguration-config-filter-s3key.html
type BucketS3KeyFilter struct {
	Rules interface{} `yaml:"Rules"`
}

// BucketS3KeyFilter validation
func (resource BucketS3KeyFilter) Validate() []error {
	errors := []error{}

	return errors
}
