package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// BucketVersioningConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfig.html
type BucketVersioningConfiguration struct {
	Status interface{} `yaml:"Status"`
}

// BucketVersioningConfiguration validation
func (resource BucketVersioningConfiguration) Validate() []error {
	errors := []error{}

	if resource.Status == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Status'"))
	}
	return errors
}
