package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// BucketNotificationFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfiguration-config-filter.html
type BucketNotificationFilter struct {
	S3Key *BucketS3KeyFilter `yaml:"S3Key"`
}

// BucketNotificationFilter validation
func (resource BucketNotificationFilter) Validate() []error {
	errs := []error{}

	if resource.S3Key == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'S3Key'"))
	} else {
		errs = append(errs, resource.S3Key.Validate()...)
	}
	return errs
}
