package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// BudgetTimePeriod Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-budgets-budget-timeperiod.html
type BudgetTimePeriod struct {
	End   interface{} `yaml:"End,omitempty"`
	Start interface{} `yaml:"Start,omitempty"`
}

// BudgetTimePeriod validation
func (resource BudgetTimePeriod) Validate() []error {
	errs := []error{}

	return errs
}
