package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// BudgetNotification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-budgets-budget-notification.html
type BudgetNotification struct {
	ComparisonOperator interface{} `yaml:"ComparisonOperator"`
	NotificationType   interface{} `yaml:"NotificationType"`
	Threshold          interface{} `yaml:"Threshold"`
	ThresholdType      interface{} `yaml:"ThresholdType,omitempty"`
}

// BudgetNotification validation
func (resource BudgetNotification) Validate() []error {
	errors := []error{}

	if resource.ComparisonOperator == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ComparisonOperator'"))
	}
	if resource.NotificationType == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'NotificationType'"))
	}
	if resource.Threshold == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Threshold'"))
	}
	return errors
}
