package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ClusterResourcesVpcConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-resourcesvpcconfig.html
type ClusterResourcesVpcConfig struct {
	SecurityGroupIds interface{} `yaml:"SecurityGroupIds,omitempty"`
	SubnetIds        interface{} `yaml:"SubnetIds"`
}

// ClusterResourcesVpcConfig validation
func (resource ClusterResourcesVpcConfig) Validate() []error {
	errs := []error{}

	if resource.SubnetIds == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'SubnetIds'"))
	}
	return errs
}
