package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ClusterScalingRule Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingrule.html
type ClusterScalingRule struct {
	Description interface{}            `yaml:"Description,omitempty"`
	Name        interface{}            `yaml:"Name"`
	Trigger     *ClusterScalingTrigger `yaml:"Trigger"`
	Action      *ClusterScalingAction  `yaml:"Action"`
}

// ClusterScalingRule validation
func (resource ClusterScalingRule) Validate() []error {
	errs := []error{}

	if resource.Name == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Name'"))
	}
	if resource.Trigger == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Trigger'"))
	} else {
		errs = append(errs, resource.Trigger.Validate()...)
	}
	if resource.Action == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Action'"))
	} else {
		errs = append(errs, resource.Action.Validate()...)
	}
	return errs
}
