package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ClusterScalingTrigger Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingtrigger.html
type ClusterScalingTrigger struct {
	CloudWatchAlarmDefinition interface{} `yaml:"CloudWatchAlarmDefinition"`
}

// ClusterScalingTrigger validation
func (resource ClusterScalingTrigger) Validate() []error {
	errors := []error{}

	return errors
}
