package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ClusterBootstrapActionConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-bootstrapactionconfig.html
type ClusterBootstrapActionConfig struct {
	Name                  interface{}                         `yaml:"Name"`
	ScriptBootstrapAction *ClusterScriptBootstrapActionConfig `yaml:"ScriptBootstrapAction"`
}

// ClusterBootstrapActionConfig validation
func (resource ClusterBootstrapActionConfig) Validate() []error {
	errs := []error{}

	if resource.Name == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Name'"))
	}
	if resource.ScriptBootstrapAction == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'ScriptBootstrapAction'"))
	} else {
		errs = append(errs, resource.ScriptBootstrapAction.Validate()...)
	}
	return errs
}
