package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// ClusterHadoopJarStepConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-hadoopjarstepconfig.html
type ClusterHadoopJarStepConfig struct {
	Jar            interface{} `yaml:"Jar"`
	MainClass      interface{} `yaml:"MainClass,omitempty"`
	Args           interface{} `yaml:"Args,omitempty"`
	StepProperties interface{} `yaml:"StepProperties,omitempty"`
}

// ClusterHadoopJarStepConfig validation
func (resource ClusterHadoopJarStepConfig) Validate() []error {
	errors := []error{}

	return errors
}
