package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ConfigurationSetEventDestinationKinesisFirehoseDestination Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-kinesisfirehosedestination.html
type ConfigurationSetEventDestinationKinesisFirehoseDestination struct {
	DeliveryStreamARN interface{} `yaml:"DeliveryStreamARN"`
	IAMRoleARN        interface{} `yaml:"IAMRoleARN"`
}

// ConfigurationSetEventDestinationKinesisFirehoseDestination validation
func (resource ConfigurationSetEventDestinationKinesisFirehoseDestination) Validate() []error {
	errs := []error{}

	if resource.DeliveryStreamARN == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DeliveryStreamARN'"))
	}
	if resource.IAMRoleARN == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'IAMRoleARN'"))
	}
	return errs
}
