package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ConnectionConnectionInput Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html
type ConnectionConnectionInput struct {
	ConnectionProperties           interface{}                               `yaml:"ConnectionProperties"`
	ConnectionType                 interface{}                               `yaml:"ConnectionType"`
	Description                    interface{}                               `yaml:"Description,omitempty"`
	Name                           interface{}                               `yaml:"Name,omitempty"`
	PhysicalConnectionRequirements *ConnectionPhysicalConnectionRequirements `yaml:"PhysicalConnectionRequirements,omitempty"`
	MatchCriteria                  interface{}                               `yaml:"MatchCriteria,omitempty"`
}

// ConnectionConnectionInput validation
func (resource ConnectionConnectionInput) Validate() []error {
	errs := []error{}

	if resource.ConnectionProperties == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'ConnectionProperties'"))
	}
	if resource.ConnectionType == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'ConnectionType'"))
	}
	return errs
}
