package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// CrawlerJdbcTarget Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-jdbctarget.html
type CrawlerJdbcTarget struct {
	ConnectionName interface{} `yaml:"ConnectionName,omitempty"`
	Path           interface{} `yaml:"Path,omitempty"`
	Exclusions     interface{} `yaml:"Exclusions,omitempty"`
}

// CrawlerJdbcTarget validation
func (resource CrawlerJdbcTarget) Validate() []error {
	errs := []error{}

	return errs
}
