package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DatasetDatasetContentVersionValue Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iotanalytics-dataset-variable-datasetcontentversionvalue.html
type DatasetDatasetContentVersionValue struct {
	DatasetName interface{} `yaml:"DatasetName,omitempty"`
}

// DatasetDatasetContentVersionValue validation
func (resource DatasetDatasetContentVersionValue) Validate() []error {
	errors := []error{}

	return errors
}
