package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// DataSourceHttpConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-datasource-httpconfig.html
type DataSourceHttpConfig struct {
	Endpoint interface{} `yaml:"Endpoint"`
}

// DataSourceHttpConfig validation
func (resource DataSourceHttpConfig) Validate() []error {
	errs := []error{}

	if resource.Endpoint == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Endpoint'"))
	}
	return errs
}
