package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DatasetContainerAction Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iotanalytics-dataset-containeraction.html
type DatasetContainerAction struct {
	ExecutionRoleArn      interface{} `yaml:"ExecutionRoleArn"`
	Image                 interface{} `yaml:"Image"`
	ResourceConfiguration interface{} `yaml:"ResourceConfiguration"`
	Variables             interface{} `yaml:"Variables,omitempty"`
}

// DatasetContainerAction validation
func (resource DatasetContainerAction) Validate() []error {
	errors := []error{}

	return errors
}
