package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DBInstanceProcessorFeature Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbinstance-processorfeature.html
type DBInstanceProcessorFeature struct {
	Name  interface{} `yaml:"Name,omitempty"`
	Value interface{} `yaml:"Value,omitempty"`
}

// DBInstanceProcessorFeature validation
func (resource DBInstanceProcessorFeature) Validate() []error {
	errors := []error{}

	return errors
}
