package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// DeliveryStreamS3DestinationConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-s3destinationconfiguration.html
type DeliveryStreamS3DestinationConfiguration struct {
	BucketARN                interface{}                             `yaml:"BucketARN"`
	CompressionFormat        interface{}                             `yaml:"CompressionFormat"`
	Prefix                   interface{}                             `yaml:"Prefix,omitempty"`
	RoleARN                  interface{}                             `yaml:"RoleARN"`
	EncryptionConfiguration  *DeliveryStreamEncryptionConfiguration  `yaml:"EncryptionConfiguration,omitempty"`
	CloudWatchLoggingOptions *DeliveryStreamCloudWatchLoggingOptions `yaml:"CloudWatchLoggingOptions,omitempty"`
	BufferingHints           *DeliveryStreamBufferingHints           `yaml:"BufferingHints"`
}

// DeliveryStreamS3DestinationConfiguration validation
func (resource DeliveryStreamS3DestinationConfiguration) Validate() []error {
	errs := []error{}

	if resource.BucketARN == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'BucketARN'"))
	}
	if resource.CompressionFormat == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'CompressionFormat'"))
	}
	if resource.RoleARN == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'RoleARN'"))
	}
	if resource.BufferingHints == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'BufferingHints'"))
	} else {
		errs = append(errs, resource.BufferingHints.Validate()...)
	}
	return errs
}
