package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// DeliveryStreamS3DestinationConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-s3destinationconfiguration.html
type DeliveryStreamS3DestinationConfiguration struct {
	BucketARN                interface{} `yaml:"BucketARN"`
	CompressionFormat        interface{} `yaml:"CompressionFormat"`
	Prefix                   interface{} `yaml:"Prefix,omitempty"`
	RoleARN                  interface{} `yaml:"RoleARN"`
	EncryptionConfiguration  interface{} `yaml:"EncryptionConfiguration,omitempty"`
	CloudWatchLoggingOptions interface{} `yaml:"CloudWatchLoggingOptions,omitempty"`
	BufferingHints           interface{} `yaml:"BufferingHints"`
}

// DeliveryStreamS3DestinationConfiguration validation
func (resource DeliveryStreamS3DestinationConfiguration) Validate() []error {
	errors := []error{}

	return errors
}
