package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// DeliveryStreamRedshiftDestinationConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-redshiftdestinationconfiguration.html
type DeliveryStreamRedshiftDestinationConfiguration struct {
	ClusterJDBCURL           interface{}                               `yaml:"ClusterJDBCURL"`
	Password                 interface{}                               `yaml:"Password"`
	RoleARN                  interface{}                               `yaml:"RoleARN"`
	Username                 interface{}                               `yaml:"Username"`
	S3Configuration          *DeliveryStreamS3DestinationConfiguration `yaml:"S3Configuration"`
	ProcessingConfiguration  *DeliveryStreamProcessingConfiguration    `yaml:"ProcessingConfiguration,omitempty"`
	CopyCommand              *DeliveryStreamCopyCommand                `yaml:"CopyCommand"`
	CloudWatchLoggingOptions *DeliveryStreamCloudWatchLoggingOptions   `yaml:"CloudWatchLoggingOptions,omitempty"`
}

// DeliveryStreamRedshiftDestinationConfiguration validation
func (resource DeliveryStreamRedshiftDestinationConfiguration) Validate() []error {
	errs := []error{}

	if resource.ClusterJDBCURL == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'ClusterJDBCURL'"))
	}
	if resource.Password == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Password'"))
	}
	if resource.RoleARN == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'RoleARN'"))
	}
	if resource.Username == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Username'"))
	}
	if resource.S3Configuration == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'S3Configuration'"))
	} else {
		errs = append(errs, resource.S3Configuration.Validate()...)
	}
	if resource.CopyCommand == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'CopyCommand'"))
	} else {
		errs = append(errs, resource.CopyCommand.Validate()...)
	}
	return errs
}
