package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DeliveryStreamExtendedS3DestinationConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-extendeds3destinationconfiguration.html
type DeliveryStreamExtendedS3DestinationConfiguration struct {
	BucketARN                interface{} `yaml:"BucketARN"`
	CompressionFormat        interface{} `yaml:"CompressionFormat"`
	Prefix                   interface{} `yaml:"Prefix"`
	RoleARN                  interface{} `yaml:"RoleARN"`
	S3BackupMode             interface{} `yaml:"S3BackupMode,omitempty"`
	S3BackupConfiguration    interface{} `yaml:"S3BackupConfiguration,omitempty"`
	ProcessingConfiguration  interface{} `yaml:"ProcessingConfiguration,omitempty"`
	EncryptionConfiguration  interface{} `yaml:"EncryptionConfiguration,omitempty"`
	CloudWatchLoggingOptions interface{} `yaml:"CloudWatchLoggingOptions,omitempty"`
	BufferingHints           interface{} `yaml:"BufferingHints"`
}

// DeliveryStreamExtendedS3DestinationConfiguration validation
func (resource DeliveryStreamExtendedS3DestinationConfiguration) Validate() []error {
	errors := []error{}

	return errors
}
