package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DeploymentGroupOnPremisesTagSet Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-onpremisestagset.html
type DeploymentGroupOnPremisesTagSet struct {
	OnPremisesTagSetList interface{} `yaml:"OnPremisesTagSetList,omitempty"`
}

// DeploymentGroupOnPremisesTagSet validation
func (resource DeploymentGroupOnPremisesTagSet) Validate() []error {
	errors := []error{}

	return errors
}
