package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DeploymentGroupTargetGroupInfo Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-targetgroupinfo.html
type DeploymentGroupTargetGroupInfo struct {
	Name interface{} `yaml:"Name,omitempty"`
}

// DeploymentGroupTargetGroupInfo validation
func (resource DeploymentGroupTargetGroupInfo) Validate() []error {
	errors := []error{}

	return errors
}
