package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DeploymentGroupLoadBalancerInfo Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-loadbalancerinfo.html
type DeploymentGroupLoadBalancerInfo struct {
	ElbInfoList         interface{} `yaml:"ElbInfoList,omitempty"`
	TargetGroupInfoList interface{} `yaml:"TargetGroupInfoList,omitempty"`
}

// DeploymentGroupLoadBalancerInfo validation
func (resource DeploymentGroupLoadBalancerInfo) Validate() []error {
	errors := []error{}

	return errors
}
