package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// DeploymentConfigMinimumHealthyHosts Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentconfig-minimumhealthyhosts.html
type DeploymentConfigMinimumHealthyHosts struct {
	Type  interface{} `yaml:"Type"`
	Value interface{} `yaml:"Value"`
}

// DeploymentConfigMinimumHealthyHosts validation
func (resource DeploymentConfigMinimumHealthyHosts) Validate() []error {
	errors := []error{}

	return errors
}
