package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DeploymentGroupTagFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-onpremisesinstancetagfilters.html
type DeploymentGroupTagFilter struct {
	Key   interface{} `yaml:"Key,omitempty"`
	Type  interface{} `yaml:"Type,omitempty"`
	Value interface{} `yaml:"Value,omitempty"`
}

// DeploymentGroupTagFilter validation
func (resource DeploymentGroupTagFilter) Validate() []error {
	errors := []error{}

	return errors
}
