package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// DistributionLogging Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-logging.html
type DistributionLogging struct {
	Bucket         interface{} `yaml:"Bucket"`
	IncludeCookies interface{} `yaml:"IncludeCookies,omitempty"`
	Prefix         interface{} `yaml:"Prefix,omitempty"`
}

// DistributionLogging validation
func (resource DistributionLogging) Validate() []error {
	errors := []error{}

	if resource.Bucket == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Bucket'"))
	}
	return errors
}
