package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DomainSnapshotOptions Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-snapshotoptions.html
type DomainSnapshotOptions struct {
	AutomatedSnapshotStartHour interface{} `yaml:"AutomatedSnapshotStartHour,omitempty"`
}

// DomainSnapshotOptions validation
func (resource DomainSnapshotOptions) Validate() []error {
	errors := []error{}

	return errors
}
