package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// DomainVPCOptions Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-vpcoptions.html
type DomainVPCOptions struct {
	SecurityGroupIds interface{} `yaml:"SecurityGroupIds,omitempty"`
	SubnetIds        interface{} `yaml:"SubnetIds,omitempty"`
}

// DomainVPCOptions validation
func (resource DomainVPCOptions) Validate() []error {
	errors := []error{}

	return errors
}
