package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// EC2FleetFleetLaunchTemplateOverridesRequest Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ec2fleet-fleetlaunchtemplateoverridesrequest.html
type EC2FleetFleetLaunchTemplateOverridesRequest struct {
	AvailabilityZone interface{} `yaml:"AvailabilityZone,omitempty"`
	InstanceType     interface{} `yaml:"InstanceType,omitempty"`
	MaxPrice         interface{} `yaml:"MaxPrice,omitempty"`
	Priority         interface{} `yaml:"Priority,omitempty"`
	SubnetId         interface{} `yaml:"SubnetId,omitempty"`
	WeightedCapacity interface{} `yaml:"WeightedCapacity,omitempty"`
}

// EC2FleetFleetLaunchTemplateOverridesRequest validation
func (resource EC2FleetFleetLaunchTemplateOverridesRequest) Validate() []error {
	errors := []error{}

	return errors
}
