package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// EndpointConfigProductionVariant Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-endpointconfig-productionvariant.html
type EndpointConfigProductionVariant struct {
	InitialInstanceCount interface{} `yaml:"InitialInstanceCount"`
	InitialVariantWeight interface{} `yaml:"InitialVariantWeight"`
	InstanceType         interface{} `yaml:"InstanceType"`
	ModelName            interface{} `yaml:"ModelName"`
	VariantName          interface{} `yaml:"VariantName"`
}

// EndpointConfigProductionVariant validation
func (resource EndpointConfigProductionVariant) Validate() []error {
	errs := []error{}

	if resource.InitialInstanceCount == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'InitialInstanceCount'"))
	}
	if resource.InitialVariantWeight == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'InitialVariantWeight'"))
	}
	if resource.InstanceType == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'InstanceType'"))
	}
	if resource.ModelName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'ModelName'"))
	}
	if resource.VariantName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'VariantName'"))
	}
	return errs
}
