package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// FunctionVpcConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html
type FunctionVpcConfig struct {
	SecurityGroupIds interface{} `yaml:"SecurityGroupIds"`
	SubnetIds        interface{} `yaml:"SubnetIds"`
}

// FunctionVpcConfig validation
func (resource FunctionVpcConfig) Validate() []error {
	errors := []error{}

	if resource.SecurityGroupIds == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'SecurityGroupIds'"))
	}
	if resource.SubnetIds == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'SubnetIds'"))
	}
	return errors
}
