package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// FunctionTracingConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-tracingconfig.html
type FunctionTracingConfig struct {
	Mode interface{} `yaml:"Mode,omitempty"`
}

// FunctionTracingConfig validation
func (resource FunctionTracingConfig) Validate() []error {
	errors := []error{}

	return errors
}
