package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// HealthCheckAlarmIdentifier Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-alarmidentifier.html
type HealthCheckAlarmIdentifier struct {
	Name   interface{} `yaml:"Name"`
	Region interface{} `yaml:"Region"`
}

// HealthCheckAlarmIdentifier validation
func (resource HealthCheckAlarmIdentifier) Validate() []error {
	errors := []error{}

	if resource.Name == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Name'"))
	}
	if resource.Region == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Region'"))
	}
	return errors
}
