package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// HostedZoneHostedZoneConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-hostedzone-hostedzoneconfig.html
type HostedZoneHostedZoneConfig struct {
	Comment interface{} `yaml:"Comment,omitempty"`
}

// HostedZoneHostedZoneConfig validation
func (resource HostedZoneHostedZoneConfig) Validate() []error {
	errs := []error{}

	return errs
}
