package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// InstanceSsmAssociation Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-ssmassociations.html
type InstanceSsmAssociation struct {
	DocumentName          interface{} `yaml:"DocumentName"`
	AssociationParameters interface{} `yaml:"AssociationParameters,omitempty"`
}

// InstanceSsmAssociation validation
func (resource InstanceSsmAssociation) Validate() []error {
	errs := []error{}

	if resource.DocumentName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DocumentName'"))
	}
	return errs
}
