package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type InstanceGroupConfig_EbsBlockDeviceConfig struct {
	VolumesPerInstance  interface{}                              `yaml:"VolumesPerInstance,omitempty"`
	VolumeSpecification *InstanceGroupConfig_VolumeSpecification `yaml:"VolumeSpecification"`
}

func (resource InstanceGroupConfig_EbsBlockDeviceConfig) Validate() []error {
	errs := []error{}

	if resource.VolumeSpecification == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'VolumeSpecification'"))
	} else {
		errs = append(errs, resource.VolumeSpecification.Validate()...)
	}
	return errs
}
