package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// InstanceBlockDeviceMapping Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-mapping.html
type InstanceBlockDeviceMapping struct {
	DeviceName  interface{}       `yaml:"DeviceName"`
	VirtualName interface{}       `yaml:"VirtualName,omitempty"`
	NoDevice    *InstanceNoDevice `yaml:"NoDevice,omitempty"`
	Ebs         *InstanceEbs      `yaml:"Ebs,omitempty"`
}

// InstanceBlockDeviceMapping validation
func (resource InstanceBlockDeviceMapping) Validate() []error {
	errs := []error{}

	if resource.DeviceName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DeviceName'"))
	}
	return errs
}
