package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// InstanceFleetConfigVolumeSpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-volumespecification.html
type InstanceFleetConfigVolumeSpecification struct {
	Iops       interface{} `yaml:"Iops,omitempty"`
	SizeInGB   interface{} `yaml:"SizeInGB"`
	VolumeType interface{} `yaml:"VolumeType"`
}

// InstanceFleetConfigVolumeSpecification validation
func (resource InstanceFleetConfigVolumeSpecification) Validate() []error {
	errors := []error{}

	return errors
}
