package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// InstanceCreditSpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-creditspecification.html
type InstanceCreditSpecification struct {
	CPUCredits interface{} `yaml:"CPUCredits,omitempty"`
}

// InstanceCreditSpecification validation
func (resource InstanceCreditSpecification) Validate() []error {
	errs := []error{}

	return errs
}
