package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// JobDefinitionVolumesHost Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-volumeshost.html
type JobDefinitionVolumesHost struct {
	SourcePath interface{} `yaml:"SourcePath,omitempty"`
}

// JobDefinitionVolumesHost validation
func (resource JobDefinitionVolumesHost) Validate() []error {
	errors := []error{}

	return errors
}
