package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// JobDefinitionVolumes Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-volumes.html
type JobDefinitionVolumes struct {
	Name interface{}               `yaml:"Name,omitempty"`
	Host *JobDefinitionVolumesHost `yaml:"Host,omitempty"`
}

// JobDefinitionVolumes validation
func (resource JobDefinitionVolumes) Validate() []error {
	errs := []error{}

	return errs
}
