package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// JobDefinitionEnvironment Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-environment.html
type JobDefinitionEnvironment struct {
	Name  interface{} `yaml:"Name,omitempty"`
	Value interface{} `yaml:"Value,omitempty"`
}

// JobDefinitionEnvironment validation
func (resource JobDefinitionEnvironment) Validate() []error {
	errs := []error{}

	return errs
}
