package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// JobJobCommand Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-jobcommand.html
type JobJobCommand struct {
	Name           interface{} `yaml:"Name,omitempty"`
	ScriptLocation interface{} `yaml:"ScriptLocation,omitempty"`
}

// JobJobCommand validation
func (resource JobJobCommand) Validate() []error {
	errors := []error{}

	return errors
}
