package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// LaunchTemplateCpuOptions Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-cpuoptions.html
type LaunchTemplateCpuOptions struct {
	CoreCount      interface{} `yaml:"CoreCount,omitempty"`
	ThreadsPerCore interface{} `yaml:"ThreadsPerCore,omitempty"`
}

// LaunchTemplateCpuOptions validation
func (resource LaunchTemplateCpuOptions) Validate() []error {
	errors := []error{}

	return errors
}
