package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// LaunchTemplateIpv6Add Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-ipv6add.html
type LaunchTemplateIpv6Add struct {
	Ipv6Address interface{} `yaml:"Ipv6Address,omitempty"`
}

// LaunchTemplateIpv6Add validation
func (resource LaunchTemplateIpv6Add) Validate() []error {
	errors := []error{}

	return errors
}
