package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// LaunchTemplateTagSpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html
type LaunchTemplateTagSpecification struct {
	ResourceType interface{} `yaml:"ResourceType,omitempty"`
	Tags         interface{} `yaml:"Tags,omitempty"`
}

// LaunchTemplateTagSpecification validation
func (resource LaunchTemplateTagSpecification) Validate() []error {
	errors := []error{}

	return errors
}
