package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// LayerLifecycleEventConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opsworks-layer-lifecycleeventconfiguration.html
type LayerLifecycleEventConfiguration struct {
	ShutdownEventConfiguration *LayerShutdownEventConfiguration `yaml:"ShutdownEventConfiguration,omitempty"`
}

// LayerLifecycleEventConfiguration validation
func (resource LayerLifecycleEventConfiguration) Validate() []error {
	errors := []error{}

	return errors
}
