package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// ListenerRedirectConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-redirectconfig.html
type ListenerRedirectConfig struct {
	Host       interface{} `yaml:"Host,omitempty"`
	Path       interface{} `yaml:"Path,omitempty"`
	Port       interface{} `yaml:"Port,omitempty"`
	Protocol   interface{} `yaml:"Protocol,omitempty"`
	Query      interface{} `yaml:"Query,omitempty"`
	StatusCode interface{} `yaml:"StatusCode"`
}

// ListenerRedirectConfig validation
func (resource ListenerRedirectConfig) Validate() []error {
	errors := []error{}

	return errors
}
