package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// LoadBalancerConnectionSettings Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-connectionsettings.html
type LoadBalancerConnectionSettings struct {
	IdleTimeout interface{} `yaml:"IdleTimeout"`
}

// LoadBalancerConnectionSettings validation
func (resource LoadBalancerConnectionSettings) Validate() []error {
	errors := []error{}

	return errors
}
