package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// LoadBalancerConnectionSettings Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-connectionsettings.html
type LoadBalancerConnectionSettings struct {
	IdleTimeout interface{} `yaml:"IdleTimeout"`
}

// LoadBalancerConnectionSettings validation
func (resource LoadBalancerConnectionSettings) Validate() []error {
	errs := []error{}

	if resource.IdleTimeout == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'IdleTimeout'"))
	}
	return errs
}
