package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// LoadBalancerAccessLoggingPolicy Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-accessloggingpolicy.html
type LoadBalancerAccessLoggingPolicy struct {
	EmitInterval   interface{} `yaml:"EmitInterval,omitempty"`
	Enabled        interface{} `yaml:"Enabled"`
	S3BucketName   interface{} `yaml:"S3BucketName"`
	S3BucketPrefix interface{} `yaml:"S3BucketPrefix,omitempty"`
}

// LoadBalancerAccessLoggingPolicy validation
func (resource LoadBalancerAccessLoggingPolicy) Validate() []error {
	errors := []error{}

	if resource.Enabled == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Enabled'"))
	}
	if resource.S3BucketName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'S3BucketName'"))
	}
	return errors
}
