package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// MaintenanceWindowTaskMaintenanceWindowLambdaParameters Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ssm-maintenancewindowtask-maintenancewindowlambdaparameters.html
type MaintenanceWindowTaskMaintenanceWindowLambdaParameters struct {
	ClientContext interface{} `yaml:"ClientContext,omitempty"`
	Payload       interface{} `yaml:"Payload,omitempty"`
	Qualifier     interface{} `yaml:"Qualifier,omitempty"`
}

// MaintenanceWindowTaskMaintenanceWindowLambdaParameters validation
func (resource MaintenanceWindowTaskMaintenanceWindowLambdaParameters) Validate() []error {
	errors := []error{}

	return errors
}
