package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type MaintenanceWindowTask_MaintenanceWindowLambdaParameters struct {
	ClientContext interface{} `yaml:"ClientContext,omitempty"`
	Payload       interface{} `yaml:"Payload,omitempty"`
	Qualifier     interface{} `yaml:"Qualifier,omitempty"`
}

func (resource MaintenanceWindowTask_MaintenanceWindowLambdaParameters) Validate() []error {
	errs := []error{}

	return errs
}
