package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type MaintenanceWindowTask_MaintenanceWindowStepFunctionsParameters struct {
	Input interface{} `yaml:"Input,omitempty"`
	Name  interface{} `yaml:"Name,omitempty"`
}

func (resource MaintenanceWindowTask_MaintenanceWindowStepFunctionsParameters) Validate() []error {
	errs := []error{}

	return errs
}
