package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type MaintenanceWindowTask_TaskInvocationParameters struct {
	MaintenanceWindowStepFunctionsParameters *MaintenanceWindowTask_MaintenanceWindowStepFunctionsParameters `yaml:"MaintenanceWindowStepFunctionsParameters,omitempty"`
	MaintenanceWindowRunCommandParameters    *MaintenanceWindowTask_MaintenanceWindowRunCommandParameters    `yaml:"MaintenanceWindowRunCommandParameters,omitempty"`
	MaintenanceWindowLambdaParameters        *MaintenanceWindowTask_MaintenanceWindowLambdaParameters        `yaml:"MaintenanceWindowLambdaParameters,omitempty"`
	MaintenanceWindowAutomationParameters    *MaintenanceWindowTask_MaintenanceWindowAutomationParameters    `yaml:"MaintenanceWindowAutomationParameters,omitempty"`
}

func (resource MaintenanceWindowTask_TaskInvocationParameters) Validate() []error {
	errs := []error{}

	return errs
}
