package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// MethodIntegrationResponse Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration-integrationresponse.html
type MethodIntegrationResponse struct {
	ContentHandling    interface{} `yaml:"ContentHandling,omitempty"`
	SelectionPattern   interface{} `yaml:"SelectionPattern,omitempty"`
	StatusCode         interface{} `yaml:"StatusCode"`
	ResponseParameters interface{} `yaml:"ResponseParameters,omitempty"`
	ResponseTemplates  interface{} `yaml:"ResponseTemplates,omitempty"`
}

// MethodIntegrationResponse validation
func (resource MethodIntegrationResponse) Validate() []error {
	errors := []error{}

	return errors
}
