package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// OptionGroupOptionSetting Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-optiongroup-optionconfigurations-optionsettings.html
type OptionGroupOptionSetting struct {
	Name  interface{} `yaml:"Name,omitempty"`
	Value interface{} `yaml:"Value,omitempty"`
}

// OptionGroupOptionSetting validation
func (resource OptionGroupOptionSetting) Validate() []error {
	errors := []error{}

	return errors
}
