package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type Partition_Order struct {
	Column    interface{} `yaml:"Column"`
	SortOrder interface{} `yaml:"SortOrder,omitempty"`
}

func (resource Partition_Order) Validate() []error {
	errs := []error{}

	if resource.Column == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Column'"))
	}
	return errs
}
