package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// PatchBaselinePatchFilterGroup Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ssm-patchbaseline-patchfiltergroup.html
type PatchBaselinePatchFilterGroup struct {
	PatchFilters interface{} `yaml:"PatchFilters,omitempty"`
}

// PatchBaselinePatchFilterGroup validation
func (resource PatchBaselinePatchFilterGroup) Validate() []error {
	errs := []error{}

	return errs
}
