package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// PipelineActionTypeId Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions-actiontypeid.html
type PipelineActionTypeId struct {
	Category interface{} `yaml:"Category"`
	Owner    interface{} `yaml:"Owner"`
	Provider interface{} `yaml:"Provider"`
	Version  interface{} `yaml:"Version"`
}

// PipelineActionTypeId validation
func (resource PipelineActionTypeId) Validate() []error {
	errs := []error{}

	if resource.Category == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Category'"))
	}
	if resource.Owner == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Owner'"))
	}
	if resource.Provider == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Provider'"))
	}
	if resource.Version == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Version'"))
	}
	return errs
}
