package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// PipelineDatastore Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iotanalytics-pipeline-datastore.html
type PipelineDatastore struct {
	DatastoreName interface{} `yaml:"DatastoreName,omitempty"`
	Name          interface{} `yaml:"Name,omitempty"`
}

// PipelineDatastore validation
func (resource PipelineDatastore) Validate() []error {
	errors := []error{}

	return errors
}
