package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// PipelineActionDeclaration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html
type PipelineActionDeclaration struct {
	Configuration   interface{} `yaml:"Configuration,omitempty"`
	Name            interface{} `yaml:"Name"`
	Region          interface{} `yaml:"Region,omitempty"`
	RoleArn         interface{} `yaml:"RoleArn,omitempty"`
	RunOrder        interface{} `yaml:"RunOrder,omitempty"`
	InputArtifacts  interface{} `yaml:"InputArtifacts,omitempty"`
	OutputArtifacts interface{} `yaml:"OutputArtifacts,omitempty"`
	ActionTypeId    interface{} `yaml:"ActionTypeId"`
}

// PipelineActionDeclaration validation
func (resource PipelineActionDeclaration) Validate() []error {
	errors := []error{}

	return errors
}
