package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ProjectS3LogsConfig Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-s3logsconfig.html
type ProjectS3LogsConfig struct {
	Location interface{} `yaml:"Location,omitempty"`
	Status   interface{} `yaml:"Status"`
}

// ProjectS3LogsConfig validation
func (resource ProjectS3LogsConfig) Validate() []error {
	errors := []error{}

	return errors
}
