package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ProjectProjectCache Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectcache.html
type ProjectProjectCache struct {
	Location interface{} `yaml:"Location,omitempty"`
	Type     interface{} `yaml:"Type"`
}

// ProjectProjectCache validation
func (resource ProjectProjectCache) Validate() []error {
	errors := []error{}

	if resource.Type == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Type'"))
	}
	return errors
}
