package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ReceiptFilterFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-receiptfilter-filter.html
type ReceiptFilterFilter struct {
	Name     interface{}            `yaml:"Name,omitempty"`
	IpFilter *ReceiptFilterIpFilter `yaml:"IpFilter"`
}

// ReceiptFilterFilter validation
func (resource ReceiptFilterFilter) Validate() []error {
	errs := []error{}

	if resource.IpFilter == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'IpFilter'"))
	} else {
		errs = append(errs, resource.IpFilter.Validate()...)
	}
	return errs
}
