package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ReceiptFilterFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-receiptfilter-filter.html
type ReceiptFilterFilter struct {
	Name     interface{}            `yaml:"Name,omitempty"`
	IpFilter *ReceiptFilterIpFilter `yaml:"IpFilter"`
}

// ReceiptFilterFilter validation
func (resource ReceiptFilterFilter) Validate() []error {
	errors := []error{}

	if resource.IpFilter == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'IpFilter'"))
	} else {
		errors = append(errors, resource.IpFilter.Validate()...)
	}
	return errors
}
