package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ReceiptRuleLambdaAction Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-receiptrule-lambdaaction.html
type ReceiptRuleLambdaAction struct {
	FunctionArn    interface{} `yaml:"FunctionArn"`
	InvocationType interface{} `yaml:"InvocationType,omitempty"`
	TopicArn       interface{} `yaml:"TopicArn,omitempty"`
}

// ReceiptRuleLambdaAction validation
func (resource ReceiptRuleLambdaAction) Validate() []error {
	errs := []error{}

	if resource.FunctionArn == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'FunctionArn'"))
	}
	return errs
}
