package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// RecordSetGroupAliasTarget Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
type RecordSetGroupAliasTarget struct {
	DNSName              interface{} `yaml:"DNSName"`
	EvaluateTargetHealth interface{} `yaml:"EvaluateTargetHealth,omitempty"`
	HostedZoneId         interface{} `yaml:"HostedZoneId"`
}

// RecordSetGroupAliasTarget validation
func (resource RecordSetGroupAliasTarget) Validate() []error {
	errs := []error{}

	if resource.DNSName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DNSName'"))
	}
	if resource.HostedZoneId == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'HostedZoneId'"))
	}
	return errs
}
