package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// RuleRunCommandParameters Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-runcommandparameters.html
type RuleRunCommandParameters struct {
	RunCommandTargets interface{} `yaml:"RunCommandTargets"`
}

// RuleRunCommandParameters validation
func (resource RuleRunCommandParameters) Validate() []error {
	errs := []error{}

	if resource.RunCommandTargets == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'RunCommandTargets'"))
	}
	return errs
}
