package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// RuleInputTransformer Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-inputtransformer.html
type RuleInputTransformer struct {
	InputTemplate interface{} `yaml:"InputTemplate"`
	InputPathsMap interface{} `yaml:"InputPathsMap,omitempty"`
}

// RuleInputTransformer validation
func (resource RuleInputTransformer) Validate() []error {
	errors := []error{}

	if resource.InputTemplate == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'InputTemplate'"))
	}
	return errors
}
