package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ScalingPlanTagFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-tagfilter.html
type ScalingPlanTagFilter struct {
	Key    interface{} `yaml:"Key"`
	Values interface{} `yaml:"Values,omitempty"`
}

// ScalingPlanTagFilter validation
func (resource ScalingPlanTagFilter) Validate() []error {
	errors := []error{}

	if resource.Key == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Key'"))
	}
	return errors
}
