package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type ScalableTarget_ScalableTargetAction struct {
	MaxCapacity interface{} `yaml:"MaxCapacity,omitempty"`
	MinCapacity interface{} `yaml:"MinCapacity,omitempty"`
}

func (resource ScalableTarget_ScalableTargetAction) Validate() []error {
	errs := []error{}

	return errs
}
