package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// ServerEngineAttribute Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opsworkscm-server-engineattribute.html
type ServerEngineAttribute struct {
	Name  interface{} `yaml:"Name,omitempty"`
	Value interface{} `yaml:"Value,omitempty"`
}

// ServerEngineAttribute validation
func (resource ServerEngineAttribute) Validate() []error {
	errors := []error{}

	return errors
}
