package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// ServicePlacementConstraint Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-placementconstraint.html
type ServicePlacementConstraint struct {
	Expression interface{} `yaml:"Expression,omitempty"`
	Type       interface{} `yaml:"Type"`
}

// ServicePlacementConstraint validation
func (resource ServicePlacementConstraint) Validate() []error {
	errors := []error{}

	if resource.Type == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Type'"))
	}
	return errors
}
