package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// SkillOverrides Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ask-skill-overrides.html
type SkillOverrides struct {
	Manifest interface{} `yaml:"Manifest,omitempty"`
}

// SkillOverrides validation
func (resource SkillOverrides) Validate() []error {
	errors := []error{}

	return errors
}
