package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// SpotFleetPrivateIpAddressSpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-networkinterfaces-privateipaddresses.html
type SpotFleetPrivateIpAddressSpecification struct {
	Primary          interface{} `yaml:"Primary,omitempty"`
	PrivateIpAddress interface{} `yaml:"PrivateIpAddress"`
}

// SpotFleetPrivateIpAddressSpecification validation
func (resource SpotFleetPrivateIpAddressSpecification) Validate() []error {
	errors := []error{}

	return errors
}
