package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// SpotFleetSpotFleetMonitoring Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-monitoring.html
type SpotFleetSpotFleetMonitoring struct {
	Enabled interface{} `yaml:"Enabled,omitempty"`
}

// SpotFleetSpotFleetMonitoring validation
func (resource SpotFleetSpotFleetMonitoring) Validate() []error {
	errs := []error{}

	return errs
}
