package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// SpotFleetLaunchTemplateOverrides Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-launchtemplateoverrides.html
type SpotFleetLaunchTemplateOverrides struct {
	AvailabilityZone interface{} `yaml:"AvailabilityZone,omitempty"`
	InstanceType     interface{} `yaml:"InstanceType,omitempty"`
	SpotPrice        interface{} `yaml:"SpotPrice,omitempty"`
	SubnetId         interface{} `yaml:"SubnetId,omitempty"`
	WeightedCapacity interface{} `yaml:"WeightedCapacity,omitempty"`
}

// SpotFleetLaunchTemplateOverrides validation
func (resource SpotFleetLaunchTemplateOverrides) Validate() []error {
	errs := []error{}

	return errs
}
