package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// SpotFleetBlockDeviceMapping Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-blockdevicemappings.html
type SpotFleetBlockDeviceMapping struct {
	DeviceName  interface{}              `yaml:"DeviceName"`
	NoDevice    interface{}              `yaml:"NoDevice,omitempty"`
	VirtualName interface{}              `yaml:"VirtualName,omitempty"`
	Ebs         *SpotFleetEbsBlockDevice `yaml:"Ebs,omitempty"`
}

// SpotFleetBlockDeviceMapping validation
func (resource SpotFleetBlockDeviceMapping) Validate() []error {
	errors := []error{}

	if resource.DeviceName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'DeviceName'"))
	}
	return errors
}
