package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// SpotFleetSpotFleetLaunchSpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications.html
type SpotFleetSpotFleetLaunchSpecification struct {
	EbsOptimized        interface{}                               `yaml:"EbsOptimized,omitempty"`
	ImageId             interface{}                               `yaml:"ImageId"`
	InstanceType        interface{}                               `yaml:"InstanceType"`
	KernelId            interface{}                               `yaml:"KernelId,omitempty"`
	KeyName             interface{}                               `yaml:"KeyName,omitempty"`
	RamdiskId           interface{}                               `yaml:"RamdiskId,omitempty"`
	SpotPrice           interface{}                               `yaml:"SpotPrice,omitempty"`
	SubnetId            interface{}                               `yaml:"SubnetId,omitempty"`
	UserData            interface{}                               `yaml:"UserData,omitempty"`
	WeightedCapacity    interface{}                               `yaml:"WeightedCapacity,omitempty"`
	Placement           *SpotFleetSpotPlacement                   `yaml:"Placement,omitempty"`
	Monitoring          *SpotFleetSpotFleetMonitoring             `yaml:"Monitoring,omitempty"`
	BlockDeviceMappings interface{}                               `yaml:"BlockDeviceMappings,omitempty"`
	NetworkInterfaces   interface{}                               `yaml:"NetworkInterfaces,omitempty"`
	SecurityGroups      interface{}                               `yaml:"SecurityGroups,omitempty"`
	TagSpecifications   interface{}                               `yaml:"TagSpecifications,omitempty"`
	IamInstanceProfile  *SpotFleetIamInstanceProfileSpecification `yaml:"IamInstanceProfile,omitempty"`
}

// SpotFleetSpotFleetLaunchSpecification validation
func (resource SpotFleetSpotFleetLaunchSpecification) Validate() []error {
	errors := []error{}

	if resource.ImageId == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ImageId'"))
	}
	if resource.InstanceType == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'InstanceType'"))
	}
	return errors
}
