package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// SqlInjectionMatchSetSqlInjectionMatchTuple Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waf-sqlinjectionmatchset-sqlinjectionmatchtuples.html
type SqlInjectionMatchSetSqlInjectionMatchTuple struct {
	TextTransformation interface{} `yaml:"TextTransformation"`
	FieldToMatch       interface{} `yaml:"FieldToMatch"`
}

// SqlInjectionMatchSetSqlInjectionMatchTuple validation
func (resource SqlInjectionMatchSetSqlInjectionMatchTuple) Validate() []error {
	errors := []error{}

	return errors
}
