package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// StackElasticIp Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opsworks-stack-elasticip.html
type StackElasticIp struct {
	Ip   interface{} `yaml:"Ip"`
	Name interface{} `yaml:"Name,omitempty"`
}

// StackElasticIp validation
func (resource StackElasticIp) Validate() []error {
	errs := []error{}

	if resource.Ip == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Ip'"))
	}
	return errs
}
