package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TableSSESpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html
type TableSSESpecification struct {
	SSEEnabled interface{} `yaml:"SSEEnabled"`
}

// TableSSESpecification validation
func (resource TableSSESpecification) Validate() []error {
	errors := []error{}

	if resource.SSEEnabled == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'SSEEnabled'"))
	}
	return errors
}
