package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TableTimeToLiveSpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-timetolivespecification.html
type TableTimeToLiveSpecification struct {
	AttributeName interface{} `yaml:"AttributeName"`
	Enabled       interface{} `yaml:"Enabled"`
}

// TableTimeToLiveSpecification validation
func (resource TableTimeToLiveSpecification) Validate() []error {
	errors := []error{}

	if resource.AttributeName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'AttributeName'"))
	}
	if resource.Enabled == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Enabled'"))
	}
	return errors
}
