package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// TablePointInTimeRecoverySpecification Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-pointintimerecoveryspecification.html
type TablePointInTimeRecoverySpecification struct {
	PointInTimeRecoveryEnabled interface{} `yaml:"PointInTimeRecoveryEnabled,omitempty"`
}

// TablePointInTimeRecoverySpecification validation
func (resource TablePointInTimeRecoverySpecification) Validate() []error {
	errors := []error{}

	return errors
}
