package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// TableProjection Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-projectionobject.html
type TableProjection struct {
	ProjectionType   interface{} `yaml:"ProjectionType,omitempty"`
	NonKeyAttributes interface{} `yaml:"NonKeyAttributes,omitempty"`
}

// TableProjection validation
func (resource TableProjection) Validate() []error {
	errors := []error{}

	return errors
}
