package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type Table_SSESpecification struct {
	SSEEnabled interface{} `yaml:"SSEEnabled"`
}

func (resource Table_SSESpecification) Validate() []error {
	errs := []error{}

	if resource.SSEEnabled == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'SSEEnabled'"))
	}
	return errs
}
