package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// TableStorageDescriptor Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html
type TableStorageDescriptor struct {
	Compressed             interface{}      `yaml:"Compressed,omitempty"`
	InputFormat            interface{}      `yaml:"InputFormat,omitempty"`
	Location               interface{}      `yaml:"Location,omitempty"`
	NumberOfBuckets        interface{}      `yaml:"NumberOfBuckets,omitempty"`
	OutputFormat           interface{}      `yaml:"OutputFormat,omitempty"`
	Parameters             interface{}      `yaml:"Parameters,omitempty"`
	StoredAsSubDirectories interface{}      `yaml:"StoredAsSubDirectories,omitempty"`
	SkewedInfo             *TableSkewedInfo `yaml:"SkewedInfo,omitempty"`
	SerdeInfo              *TableSerdeInfo  `yaml:"SerdeInfo,omitempty"`
	BucketColumns          interface{}      `yaml:"BucketColumns,omitempty"`
	Columns                interface{}      `yaml:"Columns,omitempty"`
	SortColumns            interface{}      `yaml:"SortColumns,omitempty"`
}

// TableStorageDescriptor validation
func (resource TableStorageDescriptor) Validate() []error {
	errors := []error{}

	return errors
}
