package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// TargetGroupTargetGroupAttribute Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html
type TargetGroupTargetGroupAttribute struct {
	Key   interface{} `yaml:"Key,omitempty"`
	Value interface{} `yaml:"Value,omitempty"`
}

// TargetGroupTargetGroupAttribute validation
func (resource TargetGroupTargetGroupAttribute) Validate() []error {
	errs := []error{}

	return errs
}
