package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type TargetGroup_TargetDescription struct {
	AvailabilityZone interface{} `yaml:"AvailabilityZone,omitempty"`
	Id               interface{} `yaml:"Id"`
	Port             interface{} `yaml:"Port,omitempty"`
}

func (resource TargetGroup_TargetDescription) Validate() []error {
	errs := []error{}

	if resource.Id == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Id'"))
	}
	return errs
}
