package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TargetGroupMatcher Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-matcher.html
type TargetGroupMatcher struct {
	HttpCode interface{} `yaml:"HttpCode"`
}

// TargetGroupMatcher validation
func (resource TargetGroupMatcher) Validate() []error {
	errors := []error{}

	if resource.HttpCode == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'HttpCode'"))
	}
	return errors
}
