package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TaskDefinitionHostEntry Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions-hostentry.html
type TaskDefinitionHostEntry struct {
	Hostname  interface{} `yaml:"Hostname"`
	IpAddress interface{} `yaml:"IpAddress"`
}

// TaskDefinitionHostEntry validation
func (resource TaskDefinitionHostEntry) Validate() []error {
	errs := []error{}

	if resource.Hostname == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Hostname'"))
	}
	if resource.IpAddress == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'IpAddress'"))
	}
	return errs
}
