package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type TaskDefinition_HostEntry struct {
	Hostname  interface{} `yaml:"Hostname"`
	IpAddress interface{} `yaml:"IpAddress"`
}

func (resource TaskDefinition_HostEntry) Validate() []error {
	errs := []error{}

	if resource.Hostname == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Hostname'"))
	}
	if resource.IpAddress == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'IpAddress'"))
	}
	return errs
}
