package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type TaskDefinition_LinuxParameters struct {
	InitProcessEnabled interface{}                        `yaml:"InitProcessEnabled,omitempty"`
	Devices            interface{}                        `yaml:"Devices,omitempty"`
	Capabilities       *TaskDefinition_KernelCapabilities `yaml:"Capabilities,omitempty"`
}

func (resource TaskDefinition_LinuxParameters) Validate() []error {
	errs := []error{}

	return errs
}
