package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type TaskDefinition_VolumeFrom struct {
	ReadOnly        interface{} `yaml:"ReadOnly,omitempty"`
	SourceContainer interface{} `yaml:"SourceContainer,omitempty"`
}

func (resource TaskDefinition_VolumeFrom) Validate() []error {
	errs := []error{}

	return errs
}
