package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TaskDefinitionHealthCheck Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-healthcheck.html
type TaskDefinitionHealthCheck struct {
	Interval    interface{} `yaml:"Interval,omitempty"`
	Retries     interface{} `yaml:"Retries,omitempty"`
	StartPeriod interface{} `yaml:"StartPeriod,omitempty"`
	Timeout     interface{} `yaml:"Timeout,omitempty"`
	Command     interface{} `yaml:"Command"`
}

// TaskDefinitionHealthCheck validation
func (resource TaskDefinitionHealthCheck) Validate() []error {
	errs := []error{}

	if resource.Command == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Command'"))
	}
	return errs
}
