package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// TaskDefinitionVolumeFrom Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions-volumesfrom.html
type TaskDefinitionVolumeFrom struct {
	ReadOnly        interface{} `yaml:"ReadOnly,omitempty"`
	SourceContainer interface{} `yaml:"SourceContainer,omitempty"`
}

// TaskDefinitionVolumeFrom validation
func (resource TaskDefinitionVolumeFrom) Validate() []error {
	errors := []error{}

	return errors
}
