package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type Thing_AttributePayload struct {
	Attributes interface{} `yaml:"Attributes,omitempty"`
}

func (resource Thing_AttributePayload) Validate() []error {
	errs := []error{}

	return errs
}
