package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TopicRuleCloudwatchAlarmAction Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-cloudwatchalarmaction.html
type TopicRuleCloudwatchAlarmAction struct {
	AlarmName   interface{} `yaml:"AlarmName"`
	RoleArn     interface{} `yaml:"RoleArn"`
	StateReason interface{} `yaml:"StateReason"`
	StateValue  interface{} `yaml:"StateValue"`
}

// TopicRuleCloudwatchAlarmAction validation
func (resource TopicRuleCloudwatchAlarmAction) Validate() []error {
	errors := []error{}

	if resource.AlarmName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'AlarmName'"))
	}
	if resource.RoleArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'RoleArn'"))
	}
	if resource.StateReason == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'StateReason'"))
	}
	if resource.StateValue == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'StateValue'"))
	}
	return errors
}
