package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TopicRuleCloudwatchMetricAction Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-cloudwatchmetricaction.html
type TopicRuleCloudwatchMetricAction struct {
	MetricName      interface{} `yaml:"MetricName"`
	MetricNamespace interface{} `yaml:"MetricNamespace"`
	MetricTimestamp interface{} `yaml:"MetricTimestamp,omitempty"`
	MetricUnit      interface{} `yaml:"MetricUnit"`
	MetricValue     interface{} `yaml:"MetricValue"`
	RoleArn         interface{} `yaml:"RoleArn"`
}

// TopicRuleCloudwatchMetricAction validation
func (resource TopicRuleCloudwatchMetricAction) Validate() []error {
	errors := []error{}

	if resource.MetricName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'MetricName'"))
	}
	if resource.MetricNamespace == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'MetricNamespace'"))
	}
	if resource.MetricUnit == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'MetricUnit'"))
	}
	if resource.MetricValue == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'MetricValue'"))
	}
	if resource.RoleArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'RoleArn'"))
	}
	return errors
}
