package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// TopicRuleCloudwatchAlarmAction Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-cloudwatchalarmaction.html
type TopicRuleCloudwatchAlarmAction struct {
	AlarmName   interface{} `yaml:"AlarmName"`
	RoleArn     interface{} `yaml:"RoleArn"`
	StateReason interface{} `yaml:"StateReason"`
	StateValue  interface{} `yaml:"StateValue"`
}

// TopicRuleCloudwatchAlarmAction validation
func (resource TopicRuleCloudwatchAlarmAction) Validate() []error {
	errors := []error{}

	return errors
}
