package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// UserPoolPasswordPolicy Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html
type UserPoolPasswordPolicy struct {
	MinimumLength    interface{} `yaml:"MinimumLength,omitempty"`
	RequireLowercase interface{} `yaml:"RequireLowercase,omitempty"`
	RequireNumbers   interface{} `yaml:"RequireNumbers,omitempty"`
	RequireSymbols   interface{} `yaml:"RequireSymbols,omitempty"`
	RequireUppercase interface{} `yaml:"RequireUppercase,omitempty"`
}

// UserPoolPasswordPolicy validation
func (resource UserPoolPasswordPolicy) Validate() []error {
	errs := []error{}

	return errs
}
