package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

// WebACLActivatedRule Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waf-webacl-rules.html
type WebACLActivatedRule struct {
	Priority interface{}      `yaml:"Priority"`
	RuleId   interface{}      `yaml:"RuleId"`
	Action   *WebACLWafAction `yaml:"Action"`
}

// WebACLActivatedRule validation
func (resource WebACLActivatedRule) Validate() []error {
	errors := []error{}

	if resource.Priority == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Priority'"))
	}
	if resource.RuleId == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'RuleId'"))
	}
	if resource.Action == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Action'"))
	} else {
		errors = append(errors, resource.Action.Validate()...)
	}
	return errors
}
