package properties

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

// WebhookWebhookAuthConfiguration Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-webhook-webhookauthconfiguration.html
type WebhookWebhookAuthConfiguration struct {
	AllowedIPRange interface{} `yaml:"AllowedIPRange,omitempty"`
	SecretToken    interface{} `yaml:"SecretToken,omitempty"`
}

// WebhookWebhookAuthConfiguration validation
func (resource WebhookWebhookAuthConfiguration) Validate() []error {
	errors := []error{}

	return errors
}
