package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type Application_JSONMappingParameters struct {
	RecordRowPath interface{} `yaml:"RecordRowPath"`
}

func (resource Application_JSONMappingParameters) Validate() []error {
	errs := []error{}

	if resource.RecordRowPath == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'RecordRowPath'"))
	}
	return errs
}
