package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type Instance_BlockDeviceMapping struct {
	DeviceName  interface{}        `yaml:"DeviceName"`
	VirtualName interface{}        `yaml:"VirtualName,omitempty"`
	NoDevice    *Instance_NoDevice `yaml:"NoDevice,omitempty"`
	Ebs         *Instance_Ebs      `yaml:"Ebs,omitempty"`
}

func (resource Instance_BlockDeviceMapping) Validate() []error {
	errs := []error{}

	if resource.DeviceName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DeviceName'"))
	}
	return errs
}
