package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type LaunchTemplate_Monitoring struct {
	Enabled interface{} `yaml:"Enabled,omitempty"`
}

func (resource LaunchTemplate_Monitoring) Validate() []error {
	errs := []error{}

	return errs
}
