package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type LaunchTemplate_CreditSpecification struct {
	CpuCredits interface{} `yaml:"CpuCredits,omitempty"`
}

func (resource LaunchTemplate_CreditSpecification) Validate() []error {
	errs := []error{}

	return errs
}
