package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type LaunchTemplate_PrivateIpAdd struct {
	Primary          interface{} `yaml:"Primary,omitempty"`
	PrivateIpAddress interface{} `yaml:"PrivateIpAddress,omitempty"`
}

func (resource LaunchTemplate_PrivateIpAdd) Validate() []error {
	errs := []error{}

	return errs
}
