package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type Repository_RepositoryTrigger struct {
	CustomData     interface{} `yaml:"CustomData,omitempty"`
	DestinationArn interface{} `yaml:"DestinationArn,omitempty"`
	Name           interface{} `yaml:"Name,omitempty"`
	Branches       interface{} `yaml:"Branches,omitempty"`
	Events         interface{} `yaml:"Events,omitempty"`
}

func (resource Repository_RepositoryTrigger) Validate() []error {
	errs := []error{}

	return errs
}
