package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

type TaskDefinition_MountPoint struct {
	ContainerPath interface{} `yaml:"ContainerPath,omitempty"`
	ReadOnly      interface{} `yaml:"ReadOnly,omitempty"`
	SourceVolume  interface{} `yaml:"SourceVolume,omitempty"`
}

func (resource TaskDefinition_MountPoint) Validate() []error {
	errs := []error{}

	return errs
}
