package properties

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import "fmt"

type TaskDefinition_Device struct {
	ContainerPath interface{} `yaml:"ContainerPath,omitempty"`
	HostPath      interface{} `yaml:"HostPath"`
	Permissions   interface{} `yaml:"Permissions,omitempty"`
}

func (resource TaskDefinition_Device) Validate() []error {
	errs := []error{}

	if resource.HostPath == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'HostPath'"))
	}
	return errs
}
