package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// ApplicationAutoScalingScalableTarget Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html
type ApplicationAutoScalingScalableTarget struct {
	Type       string                                         `yaml:"Type"`
	Properties ApplicationAutoScalingScalableTargetProperties `yaml:"Properties"`
	Condition  interface{}                                    `yaml:"Condition,omitempty"`
	Metadata   interface{}                                    `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                                    `yaml:"DependsOn,omitempty"`
}

// ApplicationAutoScalingScalableTarget Properties
type ApplicationAutoScalingScalableTargetProperties struct {
	MaxCapacity       interface{} `yaml:"MaxCapacity"`
	MinCapacity       interface{} `yaml:"MinCapacity"`
	ResourceId        interface{} `yaml:"ResourceId"`
	RoleARN           interface{} `yaml:"RoleARN"`
	ScalableDimension interface{} `yaml:"ScalableDimension"`
	ServiceNamespace  interface{} `yaml:"ServiceNamespace"`
	ScheduledActions  interface{} `yaml:"ScheduledActions,omitempty"`
}

// NewApplicationAutoScalingScalableTarget constructor creates a new ApplicationAutoScalingScalableTarget
func NewApplicationAutoScalingScalableTarget(properties ApplicationAutoScalingScalableTargetProperties, deps ...interface{}) ApplicationAutoScalingScalableTarget {
	return ApplicationAutoScalingScalableTarget{
		Type:       "AWS::ApplicationAutoScaling::ScalableTarget",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseApplicationAutoScalingScalableTarget parses ApplicationAutoScalingScalableTarget
func ParseApplicationAutoScalingScalableTarget(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"

	// Resources
	var resource ApplicationAutoScalingScalableTarget
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	// Outputs

	outputs = types.TemplateObject{
		name: types.TemplateObject{
			"Description": name + " Object",
			"Value": map[string]interface{}{
				"Ref": name,
			},
			"Export": map[string]interface{}{
				"Name": map[string]interface{}{
					"Fn::Sub": "${AWS::StackName}-ApplicationAutoScalingScalableTarget-" + name,
				},
			},
		},
	}

	return
}

// ParseApplicationAutoScalingScalableTarget validator
func (resource ApplicationAutoScalingScalableTarget) Validate() []error {
	return resource.Properties.Validate()
}

// ParseApplicationAutoScalingScalableTargetProperties validator
func (resource ApplicationAutoScalingScalableTargetProperties) Validate() []error {
	errors := []error{}
	return errors
}
