package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// AutoScalingScalingPolicy Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html
type AutoScalingScalingPolicy struct {
	Type       string                             `yaml:"Type"`
	Properties AutoScalingScalingPolicyProperties `yaml:"Properties"`
	Condition  interface{}                        `yaml:"Condition,omitempty"`
	Metadata   interface{}                        `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                        `yaml:"DependsOn,omitempty"`
}

// AutoScalingScalingPolicy Properties
type AutoScalingScalingPolicyProperties struct {
	AdjustmentType              interface{}                                          `yaml:"AdjustmentType,omitempty"`
	AutoScalingGroupName        interface{}                                          `yaml:"AutoScalingGroupName"`
	Cooldown                    interface{}                                          `yaml:"Cooldown,omitempty"`
	EstimatedInstanceWarmup     interface{}                                          `yaml:"EstimatedInstanceWarmup,omitempty"`
	MetricAggregationType       interface{}                                          `yaml:"MetricAggregationType,omitempty"`
	MinAdjustmentMagnitude      interface{}                                          `yaml:"MinAdjustmentMagnitude,omitempty"`
	PolicyType                  interface{}                                          `yaml:"PolicyType,omitempty"`
	ScalingAdjustment           interface{}                                          `yaml:"ScalingAdjustment,omitempty"`
	TargetTrackingConfiguration *properties.ScalingPolicyTargetTrackingConfiguration `yaml:"TargetTrackingConfiguration,omitempty"`
	StepAdjustments             interface{}                                          `yaml:"StepAdjustments,omitempty"`
}

// NewAutoScalingScalingPolicy constructor creates a new AutoScalingScalingPolicy
func NewAutoScalingScalingPolicy(properties AutoScalingScalingPolicyProperties, deps ...interface{}) AutoScalingScalingPolicy {
	return AutoScalingScalingPolicy{
		Type:       "AWS::AutoScaling::ScalingPolicy",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseAutoScalingScalingPolicy parses AutoScalingScalingPolicy
func ParseAutoScalingScalingPolicy(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource AutoScalingScalingPolicy
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseAutoScalingScalingPolicy validator
func (resource AutoScalingScalingPolicy) Validate() []error {
	return resource.Properties.Validate()
}

// ParseAutoScalingScalingPolicyProperties validator
func (resource AutoScalingScalingPolicyProperties) Validate() []error {
	errors := []error{}
	if resource.AutoScalingGroupName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'AutoScalingGroupName'"))
	}
	return errors
}
