package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// BudgetsBudget Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budget.html
type BudgetsBudget struct {
	Type       string                  `yaml:"Type"`
	Properties BudgetsBudgetProperties `yaml:"Properties"`
	Condition  interface{}             `yaml:"Condition,omitempty"`
	Metadata   interface{}             `yaml:"Metadata,omitempty"`
	DependsOn  interface{}             `yaml:"DependsOn,omitempty"`
}

// BudgetsBudget Properties
type BudgetsBudgetProperties struct {
	NotificationsWithSubscribers interface{}                  `yaml:"NotificationsWithSubscribers,omitempty"`
	Budget                       *properties.BudgetBudgetData `yaml:"Budget"`
}

// NewBudgetsBudget constructor creates a new BudgetsBudget
func NewBudgetsBudget(properties BudgetsBudgetProperties, deps ...interface{}) BudgetsBudget {
	return BudgetsBudget{
		Type:       "AWS::Budgets::Budget",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseBudgetsBudget parses BudgetsBudget
func ParseBudgetsBudget(name string, data string) (cf types.TemplateObject, err error) {
	var resource BudgetsBudget
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: BudgetsBudget - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseBudgetsBudget validator
func (resource BudgetsBudget) Validate() []error {
	return resource.Properties.Validate()
}

// ParseBudgetsBudgetProperties validator
func (resource BudgetsBudgetProperties) Validate() []error {
	errs := []error{}
	if resource.Budget == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Budget'"))
	} else {
		errs = append(errs, resource.Budget.Validate()...)
	}
	return errs
}
