package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// CodePipelinePipeline Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
type CodePipelinePipeline struct {
	Type       string                         `yaml:"Type"`
	Properties CodePipelinePipelineProperties `yaml:"Properties"`
	Condition  interface{}                    `yaml:"Condition,omitempty"`
	Metadata   interface{}                    `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                    `yaml:"DependsOn,omitempty"`
}

// CodePipelinePipeline Properties
type CodePipelinePipelineProperties struct {
	Name                           interface{} `yaml:"Name,omitempty"`
	RestartExecutionOnUpdate       interface{} `yaml:"RestartExecutionOnUpdate,omitempty"`
	RoleArn                        interface{} `yaml:"RoleArn"`
	ArtifactStores                 interface{} `yaml:"ArtifactStores,omitempty"`
	DisableInboundStageTransitions interface{} `yaml:"DisableInboundStageTransitions,omitempty"`
	Stages                         interface{} `yaml:"Stages"`
	ArtifactStore                  interface{} `yaml:"ArtifactStore,omitempty"`
}

// NewCodePipelinePipeline constructor creates a new CodePipelinePipeline
func NewCodePipelinePipeline(properties CodePipelinePipelineProperties, deps ...interface{}) CodePipelinePipeline {
	return CodePipelinePipeline{
		Type:       "AWS::CodePipeline::Pipeline",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseCodePipelinePipeline parses CodePipelinePipeline
func ParseCodePipelinePipeline(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"

	// Resources
	var resource CodePipelinePipeline
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	// Outputs

	outputs = types.TemplateObject{
		name: types.TemplateObject{
			"Description": name + " Object",
			"Value": map[string]interface{}{
				"Ref": name,
			},
			"Export": map[string]interface{}{
				"Name": map[string]interface{}{
					"Fn::Sub": "${AWS::StackName}-CodePipelinePipeline-" + name,
				},
			},
		},
	}

	return
}

// ParseCodePipelinePipeline validator
func (resource CodePipelinePipeline) Validate() []error {
	return resource.Properties.Validate()
}

// ParseCodePipelinePipelineProperties validator
func (resource CodePipelinePipelineProperties) Validate() []error {
	errors := []error{}
	return errors
}
