package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// DMSReplicationInstance Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationinstance.html
type DMSReplicationInstance struct {
	Type       string                           `yaml:"Type"`
	Properties DMSReplicationInstanceProperties `yaml:"Properties"`
	Condition  interface{}                      `yaml:"Condition,omitempty"`
	Metadata   interface{}                      `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                      `yaml:"DependsOn,omitempty"`
}

// DMSReplicationInstance Properties
type DMSReplicationInstanceProperties struct {
	AllocatedStorage                 interface{} `yaml:"AllocatedStorage,omitempty"`
	AllowMajorVersionUpgrade         interface{} `yaml:"AllowMajorVersionUpgrade,omitempty"`
	AutoMinorVersionUpgrade          interface{} `yaml:"AutoMinorVersionUpgrade,omitempty"`
	AvailabilityZone                 interface{} `yaml:"AvailabilityZone,omitempty"`
	EngineVersion                    interface{} `yaml:"EngineVersion,omitempty"`
	KmsKeyId                         interface{} `yaml:"KmsKeyId,omitempty"`
	MultiAZ                          interface{} `yaml:"MultiAZ,omitempty"`
	PreferredMaintenanceWindow       interface{} `yaml:"PreferredMaintenanceWindow,omitempty"`
	PubliclyAccessible               interface{} `yaml:"PubliclyAccessible,omitempty"`
	ReplicationInstanceClass         interface{} `yaml:"ReplicationInstanceClass"`
	ReplicationInstanceIdentifier    interface{} `yaml:"ReplicationInstanceIdentifier,omitempty"`
	ReplicationSubnetGroupIdentifier interface{} `yaml:"ReplicationSubnetGroupIdentifier,omitempty"`
	Tags                             interface{} `yaml:"Tags,omitempty"`
	VpcSecurityGroupIds              interface{} `yaml:"VpcSecurityGroupIds,omitempty"`
}

// NewDMSReplicationInstance constructor creates a new DMSReplicationInstance
func NewDMSReplicationInstance(properties DMSReplicationInstanceProperties, deps ...interface{}) DMSReplicationInstance {
	return DMSReplicationInstance{
		Type:       "AWS::DMS::ReplicationInstance",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseDMSReplicationInstance parses DMSReplicationInstance
func ParseDMSReplicationInstance(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource DMSReplicationInstance
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseDMSReplicationInstance validator
func (resource DMSReplicationInstance) Validate() []error {
	return resource.Properties.Validate()
}

// ParseDMSReplicationInstanceProperties validator
func (resource DMSReplicationInstanceProperties) Validate() []error {
	errors := []error{}
	if resource.ReplicationInstanceClass == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ReplicationInstanceClass'"))
	}
	return errors
}
