package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// DMSReplicationTask Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationtask.html
type DMSReplicationTask struct {
	Type       string                       `yaml:"Type"`
	Properties DMSReplicationTaskProperties `yaml:"Properties"`
	Condition  interface{}                  `yaml:"Condition,omitempty"`
	Metadata   interface{}                  `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                  `yaml:"DependsOn,omitempty"`
}

// DMSReplicationTask Properties
type DMSReplicationTaskProperties struct {
	CdcStartTime              interface{} `yaml:"CdcStartTime,omitempty"`
	MigrationType             interface{} `yaml:"MigrationType"`
	ReplicationInstanceArn    interface{} `yaml:"ReplicationInstanceArn"`
	ReplicationTaskIdentifier interface{} `yaml:"ReplicationTaskIdentifier,omitempty"`
	ReplicationTaskSettings   interface{} `yaml:"ReplicationTaskSettings,omitempty"`
	SourceEndpointArn         interface{} `yaml:"SourceEndpointArn"`
	TableMappings             interface{} `yaml:"TableMappings"`
	TargetEndpointArn         interface{} `yaml:"TargetEndpointArn"`
	Tags                      interface{} `yaml:"Tags,omitempty"`
}

// NewDMSReplicationTask constructor creates a new DMSReplicationTask
func NewDMSReplicationTask(properties DMSReplicationTaskProperties, deps ...interface{}) DMSReplicationTask {
	return DMSReplicationTask{
		Type:       "AWS::DMS::ReplicationTask",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseDMSReplicationTask parses DMSReplicationTask
func ParseDMSReplicationTask(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource DMSReplicationTask
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseDMSReplicationTask validator
func (resource DMSReplicationTask) Validate() []error {
	return resource.Properties.Validate()
}

// ParseDMSReplicationTaskProperties validator
func (resource DMSReplicationTaskProperties) Validate() []error {
	errors := []error{}
	if resource.MigrationType == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'MigrationType'"))
	}
	if resource.ReplicationInstanceArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ReplicationInstanceArn'"))
	}
	if resource.SourceEndpointArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'SourceEndpointArn'"))
	}
	if resource.TableMappings == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'TableMappings'"))
	}
	if resource.TargetEndpointArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'TargetEndpointArn'"))
	}
	return errors
}
