package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// DMSEndpoint Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html
type DMSEndpoint struct {
	Type       string                `yaml:"Type"`
	Properties DMSEndpointProperties `yaml:"Properties"`
	Condition  interface{}           `yaml:"Condition,omitempty"`
	Metadata   interface{}           `yaml:"Metadata,omitempty"`
	DependsOn  interface{}           `yaml:"DependsOn,omitempty"`
}

// DMSEndpoint Properties
type DMSEndpointProperties struct {
	CertificateArn            interface{}                          `yaml:"CertificateArn,omitempty"`
	DatabaseName              interface{}                          `yaml:"DatabaseName,omitempty"`
	EndpointIdentifier        interface{}                          `yaml:"EndpointIdentifier,omitempty"`
	EndpointType              interface{}                          `yaml:"EndpointType"`
	EngineName                interface{}                          `yaml:"EngineName"`
	ExtraConnectionAttributes interface{}                          `yaml:"ExtraConnectionAttributes,omitempty"`
	KmsKeyId                  interface{}                          `yaml:"KmsKeyId,omitempty"`
	Password                  interface{}                          `yaml:"Password,omitempty"`
	Port                      interface{}                          `yaml:"Port,omitempty"`
	ServerName                interface{}                          `yaml:"ServerName,omitempty"`
	SslMode                   interface{}                          `yaml:"SslMode,omitempty"`
	Username                  interface{}                          `yaml:"Username,omitempty"`
	S3Settings                *properties.EndpointS3Settings       `yaml:"S3Settings,omitempty"`
	MongoDbSettings           *properties.EndpointMongoDbSettings  `yaml:"MongoDbSettings,omitempty"`
	Tags                      interface{}                          `yaml:"Tags,omitempty"`
	DynamoDbSettings          *properties.EndpointDynamoDbSettings `yaml:"DynamoDbSettings,omitempty"`
}

// NewDMSEndpoint constructor creates a new DMSEndpoint
func NewDMSEndpoint(properties DMSEndpointProperties, deps ...interface{}) DMSEndpoint {
	return DMSEndpoint{
		Type:       "AWS::DMS::Endpoint",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseDMSEndpoint parses DMSEndpoint
func ParseDMSEndpoint(ctx map[string]interface{}, name string, data string) (cf types.TemplateObject, err error) {
	var resource DMSEndpoint
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: DMSEndpoint - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseDMSEndpoint validator
func (resource DMSEndpoint) Validate() []error {
	return resource.Properties.Validate()
}

// ParseDMSEndpointProperties validator
func (resource DMSEndpointProperties) Validate() []error {
	errs := []error{}
	if resource.EndpointType == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'EndpointType'"))
	}
	if resource.EngineName == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'EngineName'"))
	}
	return errs
}
