package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// EC2TransitGatewayRouteTablePropagation Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayroutetablepropagation.html
type EC2TransitGatewayRouteTablePropagation struct {
	Type       string                                           `yaml:"Type"`
	Properties EC2TransitGatewayRouteTablePropagationProperties `yaml:"Properties"`
	Condition  interface{}                                      `yaml:"Condition,omitempty"`
	Metadata   interface{}                                      `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                                      `yaml:"DependsOn,omitempty"`
}

// EC2TransitGatewayRouteTablePropagation Properties
type EC2TransitGatewayRouteTablePropagationProperties struct {
	TransitGatewayAttachmentId interface{} `yaml:"TransitGatewayAttachmentId"`
	TransitGatewayRouteTableId interface{} `yaml:"TransitGatewayRouteTableId"`
}

// NewEC2TransitGatewayRouteTablePropagation constructor creates a new EC2TransitGatewayRouteTablePropagation
func NewEC2TransitGatewayRouteTablePropagation(properties EC2TransitGatewayRouteTablePropagationProperties, deps ...interface{}) EC2TransitGatewayRouteTablePropagation {
	return EC2TransitGatewayRouteTablePropagation{
		Type:       "AWS::EC2::TransitGatewayRouteTablePropagation",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseEC2TransitGatewayRouteTablePropagation parses EC2TransitGatewayRouteTablePropagation
func ParseEC2TransitGatewayRouteTablePropagation(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"

	// Resources
	var resource EC2TransitGatewayRouteTablePropagation
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	// Outputs

	outputs = types.TemplateObject{
		name: types.TemplateObject{
			"Description": name + " Object",
			"Value": map[string]interface{}{
				"Ref": name,
			},
			"Export": map[string]interface{}{
				"Name": map[string]interface{}{
					"Fn::Sub": "${AWS::StackName}-EC2TransitGatewayRouteTablePropagation-" + name,
				},
			},
		},
	}

	return
}

// ParseEC2TransitGatewayRouteTablePropagation validator
func (resource EC2TransitGatewayRouteTablePropagation) Validate() []error {
	return resource.Properties.Validate()
}

// ParseEC2TransitGatewayRouteTablePropagationProperties validator
func (resource EC2TransitGatewayRouteTablePropagationProperties) Validate() []error {
	errors := []error{}
	return errors
}
