package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// EC2SubnetRouteTableAssociation Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet-route-table-assoc.html
type EC2SubnetRouteTableAssociation struct {
	Type       string                                   `yaml:"Type"`
	Properties EC2SubnetRouteTableAssociationProperties `yaml:"Properties"`
	Condition  interface{}                              `yaml:"Condition,omitempty"`
	Metadata   interface{}                              `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                              `yaml:"DependsOn,omitempty"`
}

// EC2SubnetRouteTableAssociation Properties
type EC2SubnetRouteTableAssociationProperties struct {
	RouteTableId interface{} `yaml:"RouteTableId"`
	SubnetId     interface{} `yaml:"SubnetId"`
}

// NewEC2SubnetRouteTableAssociation constructor creates a new EC2SubnetRouteTableAssociation
func NewEC2SubnetRouteTableAssociation(properties EC2SubnetRouteTableAssociationProperties, deps ...interface{}) EC2SubnetRouteTableAssociation {
	return EC2SubnetRouteTableAssociation{
		Type:       "AWS::EC2::SubnetRouteTableAssociation",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseEC2SubnetRouteTableAssociation parses EC2SubnetRouteTableAssociation
func ParseEC2SubnetRouteTableAssociation(ctx map[string]interface{}, name string, data string) (cf types.TemplateObject, err error) {
	var resource EC2SubnetRouteTableAssociation
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: EC2SubnetRouteTableAssociation - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseEC2SubnetRouteTableAssociation validator
func (resource EC2SubnetRouteTableAssociation) Validate() []error {
	return resource.Properties.Validate()
}

// ParseEC2SubnetRouteTableAssociationProperties validator
func (resource EC2SubnetRouteTableAssociationProperties) Validate() []error {
	errs := []error{}
	if resource.RouteTableId == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'RouteTableId'"))
	}
	if resource.SubnetId == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'SubnetId'"))
	}
	return errs
}
