package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// EC2SpotFleet Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-spotfleet.html
type EC2SpotFleet struct {
	Type       string                 `yaml:"Type"`
	Properties EC2SpotFleetProperties `yaml:"Properties"`
	Condition  interface{}            `yaml:"Condition,omitempty"`
	Metadata   interface{}            `yaml:"Metadata,omitempty"`
	DependsOn  interface{}            `yaml:"DependsOn,omitempty"`
}

// EC2SpotFleet Properties
type EC2SpotFleetProperties struct {
	SpotFleetRequestConfigData *properties.SpotFleetSpotFleetRequestConfigData `yaml:"SpotFleetRequestConfigData"`
}

// NewEC2SpotFleet constructor creates a new EC2SpotFleet
func NewEC2SpotFleet(properties EC2SpotFleetProperties, deps ...interface{}) EC2SpotFleet {
	return EC2SpotFleet{
		Type:       "AWS::EC2::SpotFleet",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseEC2SpotFleet parses EC2SpotFleet
func ParseEC2SpotFleet(name string, data string) (cf types.TemplateObject, err error) {
	var resource EC2SpotFleet
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: EC2SpotFleet - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseEC2SpotFleet validator
func (resource EC2SpotFleet) Validate() []error {
	return resource.Properties.Validate()
}

// ParseEC2SpotFleetProperties validator
func (resource EC2SpotFleetProperties) Validate() []error {
	errs := []error{}
	if resource.SpotFleetRequestConfigData == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'SpotFleetRequestConfigData'"))
	} else {
		errs = append(errs, resource.SpotFleetRequestConfigData.Validate()...)
	}
	return errs
}
