package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// ElasticLoadBalancingV2ListenerCertificate Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listenercertificate.html
type ElasticLoadBalancingV2ListenerCertificate struct {
	Type       string                                              `yaml:"Type"`
	Properties ElasticLoadBalancingV2ListenerCertificateProperties `yaml:"Properties"`
	Condition  interface{}                                         `yaml:"Condition,omitempty"`
	Metadata   interface{}                                         `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                                         `yaml:"DependsOn,omitempty"`
}

// ElasticLoadBalancingV2ListenerCertificate Properties
type ElasticLoadBalancingV2ListenerCertificateProperties struct {
	ListenerArn  interface{} `yaml:"ListenerArn"`
	Certificates interface{} `yaml:"Certificates"`
}

// NewElasticLoadBalancingV2ListenerCertificate constructor creates a new ElasticLoadBalancingV2ListenerCertificate
func NewElasticLoadBalancingV2ListenerCertificate(properties ElasticLoadBalancingV2ListenerCertificateProperties, deps ...interface{}) ElasticLoadBalancingV2ListenerCertificate {
	return ElasticLoadBalancingV2ListenerCertificate{
		Type:       "AWS::ElasticLoadBalancingV2::ListenerCertificate",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseElasticLoadBalancingV2ListenerCertificate parses ElasticLoadBalancingV2ListenerCertificate
func ParseElasticLoadBalancingV2ListenerCertificate(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource ElasticLoadBalancingV2ListenerCertificate
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseElasticLoadBalancingV2ListenerCertificate validator
func (resource ElasticLoadBalancingV2ListenerCertificate) Validate() []error {
	return resource.Properties.Validate()
}

// ParseElasticLoadBalancingV2ListenerCertificateProperties validator
func (resource ElasticLoadBalancingV2ListenerCertificateProperties) Validate() []error {
	errors := []error{}
	if resource.ListenerArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ListenerArn'"))
	}
	if resource.Certificates == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Certificates'"))
	}
	return errors
}
