package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// GuardDutyFilter Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-filter.html
type GuardDutyFilter struct {
	Type       string                    `yaml:"Type"`
	Properties GuardDutyFilterProperties `yaml:"Properties"`
	Condition  interface{}               `yaml:"Condition,omitempty"`
	Metadata   interface{}               `yaml:"Metadata,omitempty"`
	DependsOn  interface{}               `yaml:"DependsOn,omitempty"`
}

// GuardDutyFilter Properties
type GuardDutyFilterProperties struct {
	Action          interface{}                       `yaml:"Action"`
	Description     interface{}                       `yaml:"Description"`
	DetectorId      interface{}                       `yaml:"DetectorId"`
	Name            interface{}                       `yaml:"Name,omitempty"`
	Rank            interface{}                       `yaml:"Rank"`
	FindingCriteria *properties.FilterFindingCriteria `yaml:"FindingCriteria"`
}

// NewGuardDutyFilter constructor creates a new GuardDutyFilter
func NewGuardDutyFilter(properties GuardDutyFilterProperties, deps ...interface{}) GuardDutyFilter {
	return GuardDutyFilter{
		Type:       "AWS::GuardDuty::Filter",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseGuardDutyFilter parses GuardDutyFilter
func ParseGuardDutyFilter(ctx map[string]interface{}, name string, data string) (cf types.TemplateObject, err error) {
	var resource GuardDutyFilter
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: GuardDutyFilter - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseGuardDutyFilter validator
func (resource GuardDutyFilter) Validate() []error {
	return resource.Properties.Validate()
}

// ParseGuardDutyFilterProperties validator
func (resource GuardDutyFilterProperties) Validate() []error {
	errs := []error{}
	if resource.Action == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Action'"))
	}
	if resource.Description == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Description'"))
	}
	if resource.DetectorId == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DetectorId'"))
	}
	if resource.Rank == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'Rank'"))
	}
	if resource.FindingCriteria == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'FindingCriteria'"))
	} else {
		errs = append(errs, resource.FindingCriteria.Validate()...)
	}
	return errs
}
