package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// IoTPolicy Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-policy.html
type IoTPolicy struct {
	Type       string              `yaml:"Type"`
	Properties IoTPolicyProperties `yaml:"Properties"`
	Condition  interface{}         `yaml:"Condition,omitempty"`
	Metadata   interface{}         `yaml:"Metadata,omitempty"`
	DependsOn  interface{}         `yaml:"DependsOn,omitempty"`
}

// IoTPolicy Properties
type IoTPolicyProperties struct {
	PolicyDocument interface{} `yaml:"PolicyDocument"`
	PolicyName     interface{} `yaml:"PolicyName,omitempty"`
}

// NewIoTPolicy constructor creates a new IoTPolicy
func NewIoTPolicy(properties IoTPolicyProperties, deps ...interface{}) IoTPolicy {
	return IoTPolicy{
		Type:       "AWS::IoT::Policy",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseIoTPolicy parses IoTPolicy
func ParseIoTPolicy(ctx map[string]interface{}, name string, data string) (cf types.TemplateObject, err error) {
	var resource IoTPolicy
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: IoTPolicy - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseIoTPolicy validator
func (resource IoTPolicy) Validate() []error {
	return resource.Properties.Validate()
}

// ParseIoTPolicyProperties validator
func (resource IoTPolicyProperties) Validate() []error {
	errs := []error{}
	if resource.PolicyDocument == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'PolicyDocument'"))
	}
	return errs
}
