package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// KMSAlias Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html
type KMSAlias struct {
	Type       string             `yaml:"Type"`
	Properties KMSAliasProperties `yaml:"Properties"`
	Condition  interface{}        `yaml:"Condition,omitempty"`
	Metadata   interface{}        `yaml:"Metadata,omitempty"`
	DependsOn  interface{}        `yaml:"DependsOn,omitempty"`
}

// KMSAlias Properties
type KMSAliasProperties struct {
	AliasName   interface{} `yaml:"AliasName"`
	TargetKeyId interface{} `yaml:"TargetKeyId"`
}

// NewKMSAlias constructor creates a new KMSAlias
func NewKMSAlias(properties KMSAliasProperties, deps ...interface{}) KMSAlias {
	return KMSAlias{
		Type:       "AWS::KMS::Alias",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseKMSAlias parses KMSAlias
func ParseKMSAlias(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource KMSAlias
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseKMSAlias validator
func (resource KMSAlias) Validate() []error {
	return resource.Properties.Validate()
}

// ParseKMSAliasProperties validator
func (resource KMSAliasProperties) Validate() []error {
	errors := []error{}
	if resource.AliasName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'AliasName'"))
	}
	if resource.TargetKeyId == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'TargetKeyId'"))
	}
	return errors
}
