package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// NeptuneDBParameterGroup Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbparametergroup.html
type NeptuneDBParameterGroup struct {
	Type       string                            `yaml:"Type"`
	Properties NeptuneDBParameterGroupProperties `yaml:"Properties"`
	Condition  interface{}                       `yaml:"Condition,omitempty"`
	Metadata   interface{}                       `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                       `yaml:"DependsOn,omitempty"`
}

// NeptuneDBParameterGroup Properties
type NeptuneDBParameterGroupProperties struct {
	Description interface{} `yaml:"Description"`
	Family      interface{} `yaml:"Family"`
	Name        interface{} `yaml:"Name,omitempty"`
	Parameters  interface{} `yaml:"Parameters"`
	Tags        interface{} `yaml:"Tags,omitempty"`
}

// NewNeptuneDBParameterGroup constructor creates a new NeptuneDBParameterGroup
func NewNeptuneDBParameterGroup(properties NeptuneDBParameterGroupProperties, deps ...interface{}) NeptuneDBParameterGroup {
	return NeptuneDBParameterGroup{
		Type:       "AWS::Neptune::DBParameterGroup",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseNeptuneDBParameterGroup parses NeptuneDBParameterGroup
func ParseNeptuneDBParameterGroup(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource NeptuneDBParameterGroup
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseNeptuneDBParameterGroup validator
func (resource NeptuneDBParameterGroup) Validate() []error {
	return resource.Properties.Validate()
}

// ParseNeptuneDBParameterGroupProperties validator
func (resource NeptuneDBParameterGroupProperties) Validate() []error {
	errors := []error{}
	if resource.Description == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Description'"))
	}
	if resource.Family == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Family'"))
	}
	if resource.Parameters == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Parameters'"))
	}
	return errors
}
