package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// RDSEventSubscription Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-eventsubscription.html
type RDSEventSubscription struct {
	Type       string                         `yaml:"Type"`
	Properties RDSEventSubscriptionProperties `yaml:"Properties"`
	Condition  interface{}                    `yaml:"Condition,omitempty"`
	Metadata   interface{}                    `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                    `yaml:"DependsOn,omitempty"`
}

// RDSEventSubscription Properties
type RDSEventSubscriptionProperties struct {
	Enabled         interface{} `yaml:"Enabled,omitempty"`
	SnsTopicArn     interface{} `yaml:"SnsTopicArn"`
	SourceType      interface{} `yaml:"SourceType,omitempty"`
	EventCategories interface{} `yaml:"EventCategories,omitempty"`
	SourceIds       interface{} `yaml:"SourceIds,omitempty"`
}

// NewRDSEventSubscription constructor creates a new RDSEventSubscription
func NewRDSEventSubscription(properties RDSEventSubscriptionProperties, deps ...interface{}) RDSEventSubscription {
	return RDSEventSubscription{
		Type:       "AWS::RDS::EventSubscription",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseRDSEventSubscription parses RDSEventSubscription
func ParseRDSEventSubscription(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource RDSEventSubscription
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseRDSEventSubscription validator
func (resource RDSEventSubscription) Validate() []error {
	return resource.Properties.Validate()
}

// ParseRDSEventSubscriptionProperties validator
func (resource RDSEventSubscriptionProperties) Validate() []error {
	errors := []error{}
	if resource.SnsTopicArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'SnsTopicArn'"))
	}
	return errors
}
