package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// ServiceCatalogPortfolio Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-portfolio.html
type ServiceCatalogPortfolio struct {
	Type       string                            `yaml:"Type"`
	Properties ServiceCatalogPortfolioProperties `yaml:"Properties"`
	Condition  interface{}                       `yaml:"Condition,omitempty"`
	Metadata   interface{}                       `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                       `yaml:"DependsOn,omitempty"`
}

// ServiceCatalogPortfolio Properties
type ServiceCatalogPortfolioProperties struct {
	AcceptLanguage interface{} `yaml:"AcceptLanguage,omitempty"`
	Description    interface{} `yaml:"Description,omitempty"`
	DisplayName    interface{} `yaml:"DisplayName"`
	ProviderName   interface{} `yaml:"ProviderName"`
	Tags           interface{} `yaml:"Tags,omitempty"`
}

// NewServiceCatalogPortfolio constructor creates a new ServiceCatalogPortfolio
func NewServiceCatalogPortfolio(properties ServiceCatalogPortfolioProperties, deps ...interface{}) ServiceCatalogPortfolio {
	return ServiceCatalogPortfolio{
		Type:       "AWS::ServiceCatalog::Portfolio",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseServiceCatalogPortfolio parses ServiceCatalogPortfolio
func ParseServiceCatalogPortfolio(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource ServiceCatalogPortfolio
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseServiceCatalogPortfolio validator
func (resource ServiceCatalogPortfolio) Validate() []error {
	return resource.Properties.Validate()
}

// ParseServiceCatalogPortfolioProperties validator
func (resource ServiceCatalogPortfolioProperties) Validate() []error {
	errors := []error{}
	if resource.DisplayName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'DisplayName'"))
	}
	if resource.ProviderName == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'ProviderName'"))
	}
	return errors
}
