package resources

// DO NOT EDIT: This file is autogenerated by running 'go generate'
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	"log"
)

// ServiceDiscoveryService Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-service.html
type ServiceDiscoveryService struct {
	Type       string                            `yaml:"Type"`
	Properties ServiceDiscoveryServiceProperties `yaml:"Properties"`
	Condition  interface{}                       `yaml:"Condition,omitempty"`
	Metadata   interface{}                       `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                       `yaml:"DependsOn,omitempty"`
}

// ServiceDiscoveryService Properties
type ServiceDiscoveryServiceProperties struct {
	Description       interface{}                          `yaml:"Description,omitempty"`
	Name              interface{}                          `yaml:"Name,omitempty"`
	HealthCheckConfig *properties.ServiceHealthCheckConfig `yaml:"HealthCheckConfig,omitempty"`
	DnsConfig         *properties.ServiceDnsConfig         `yaml:"DnsConfig"`
}

// NewServiceDiscoveryService constructor creates a new ServiceDiscoveryService
func NewServiceDiscoveryService(properties ServiceDiscoveryServiceProperties, deps ...interface{}) ServiceDiscoveryService {
	return ServiceDiscoveryService{
		Type:       "AWS::ServiceDiscovery::Service",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseServiceDiscoveryService parses ServiceDiscoveryService
func ParseServiceDiscoveryService(ctx map[string]interface{}, name string, data string) (cf types.TemplateObject, err error) {
	var resource ServiceDiscoveryService
	if err = yaml.Unmarshal([]byte(data), &resource); err != nil {
		return
	}
	if errs := resource.Properties.Validate(); len(errs) > 0 {
		for _, err = range errs {
			log.Println("WARNING: ServiceDiscoveryService - ", err)
		}
		return
	}
	cf = types.TemplateObject{name: resource}
	return
}

// ParseServiceDiscoveryService validator
func (resource ServiceDiscoveryService) Validate() []error {
	return resource.Properties.Validate()
}

// ParseServiceDiscoveryServiceProperties validator
func (resource ServiceDiscoveryServiceProperties) Validate() []error {
	errs := []error{}
	if resource.DnsConfig == nil {
		errs = append(errs, fmt.Errorf("Missing required field 'DnsConfig'"))
	} else {
		errs = append(errs, resource.DnsConfig.Validate()...)
	}
	return errs
}
