package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	//
	// "fmt"
	//
	//
)

// SQSQueuePolicy Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-policy.html
type SQSQueuePolicy struct {
	Type       string                   `yaml:"Type"`
	Properties SQSQueuePolicyProperties `yaml:"Properties"`
	Condition  interface{}              `yaml:"Condition,omitempty"`
	Metadata   interface{}              `yaml:"Metadata,omitempty"`
	DependsOn  interface{}              `yaml:"DependsOn,omitempty"`
}

// SQSQueuePolicy Properties
type SQSQueuePolicyProperties struct {
	PolicyDocument interface{} `yaml:"PolicyDocument"`
	Queues         interface{} `yaml:"Queues"`
}

// NewSQSQueuePolicy constructor creates a new SQSQueuePolicy
func NewSQSQueuePolicy(properties SQSQueuePolicyProperties, deps ...interface{}) SQSQueuePolicy {
	return SQSQueuePolicy{
		Type:       "AWS::SQS::QueuePolicy",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseSQSQueuePolicy parses SQSQueuePolicy
func ParseSQSQueuePolicy(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"

	// Resources
	var resource SQSQueuePolicy
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	// Outputs

	outputs = types.TemplateObject{
		name: types.TemplateObject{
			"Description": name + " Object",
			"Value": map[string]interface{}{
				"Ref": name,
			},
			"Export": map[string]interface{}{
				"Name": map[string]interface{}{
					"Fn::Sub": "${AWS::StackName}-SQSQueuePolicy-" + name,
				},
			},
		},
	}

	return
}

// ParseSQSQueuePolicy validator
func (resource SQSQueuePolicy) Validate() []error {
	return resource.Properties.Validate()
}

// ParseSQSQueuePolicyProperties validator
func (resource SQSQueuePolicyProperties) Validate() []error {
	errors := []error{}
	return errors
}
