package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
	//
	// "fmt"
	//
	//
	//"github.com/KablamoOSS/kombustion/pkg/parsers/properties"
	//
)

// SSMAssociation Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-association.html
type SSMAssociation struct {
	Type       string                   `yaml:"Type"`
	Properties SSMAssociationProperties `yaml:"Properties"`
	Condition  interface{}              `yaml:"Condition,omitempty"`
	Metadata   interface{}              `yaml:"Metadata,omitempty"`
	DependsOn  interface{}              `yaml:"DependsOn,omitempty"`
}

// SSMAssociation Properties
type SSMAssociationProperties struct {
	AssociationName    interface{} `yaml:"AssociationName,omitempty"`
	DocumentVersion    interface{} `yaml:"DocumentVersion,omitempty"`
	InstanceId         interface{} `yaml:"InstanceId,omitempty"`
	Name               interface{} `yaml:"Name"`
	ScheduleExpression interface{} `yaml:"ScheduleExpression,omitempty"`
	Parameters         interface{} `yaml:"Parameters,omitempty"`
	Targets            interface{} `yaml:"Targets,omitempty"`
	OutputLocation     interface{} `yaml:"OutputLocation,omitempty"`
}

// NewSSMAssociation constructor creates a new SSMAssociation
func NewSSMAssociation(properties SSMAssociationProperties, deps ...interface{}) SSMAssociation {
	return SSMAssociation{
		Type:       "AWS::SSM::Association",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseSSMAssociation parses SSMAssociation
func ParseSSMAssociation(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"

	// Resources
	var resource SSMAssociation
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	// Outputs

	outputs = types.TemplateObject{
		name: types.TemplateObject{
			"Description": name + " Object",
			"Value": map[string]interface{}{
				"Ref": name,
			},
			"Export": map[string]interface{}{
				"Name": map[string]interface{}{
					"Fn::Sub": "${AWS::StackName}-SSMAssociation-" + name,
				},
			},
		},
	}

	return
}

// ParseSSMAssociation validator
func (resource SSMAssociation) Validate() []error {
	return resource.Properties.Validate()
}

// ParseSSMAssociationProperties validator
func (resource SSMAssociationProperties) Validate() []error {
	errors := []error{}
	return errors
}
