package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// StepFunctionsStateMachine Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html
type StepFunctionsStateMachine struct {
	Type       string                              `yaml:"Type"`
	Properties StepFunctionsStateMachineProperties `yaml:"Properties"`
	Condition  interface{}                         `yaml:"Condition,omitempty"`
	Metadata   interface{}                         `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                         `yaml:"DependsOn,omitempty"`
}

// StepFunctionsStateMachine Properties
type StepFunctionsStateMachineProperties struct {
	DefinitionString interface{} `yaml:"DefinitionString"`
	RoleArn          interface{} `yaml:"RoleArn"`
	StateMachineName interface{} `yaml:"StateMachineName,omitempty"`
}

// NewStepFunctionsStateMachine constructor creates a new StepFunctionsStateMachine
func NewStepFunctionsStateMachine(properties StepFunctionsStateMachineProperties, deps ...interface{}) StepFunctionsStateMachine {
	return StepFunctionsStateMachine{
		Type:       "AWS::StepFunctions::StateMachine",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseStepFunctionsStateMachine parses StepFunctionsStateMachine
func ParseStepFunctionsStateMachine(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource StepFunctionsStateMachine
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseStepFunctionsStateMachine validator
func (resource StepFunctionsStateMachine) Validate() []error {
	return resource.Properties.Validate()
}

// ParseStepFunctionsStateMachineProperties validator
func (resource StepFunctionsStateMachineProperties) Validate() []error {
	errors := []error{}
	if resource.DefinitionString == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'DefinitionString'"))
	}
	if resource.RoleArn == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'RoleArn'"))
	}
	return errors
}
