package resources

// Code generated by go generate; DO NOT EDIT.
// It's generated by "github.com/KablamoOSS/kombustion/generate"

import (
	"fmt"
	"github.com/KablamoOSS/kombustion/types"
	yaml "github.com/KablamoOSS/yaml"
)

// WAFRegionalXssMatchSet Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-xssmatchset.html
type WAFRegionalXssMatchSet struct {
	Type       string                           `yaml:"Type"`
	Properties WAFRegionalXssMatchSetProperties `yaml:"Properties"`
	Condition  interface{}                      `yaml:"Condition,omitempty"`
	Metadata   interface{}                      `yaml:"Metadata,omitempty"`
	DependsOn  interface{}                      `yaml:"DependsOn,omitempty"`
}

// WAFRegionalXssMatchSet Properties
type WAFRegionalXssMatchSetProperties struct {
	Name           interface{} `yaml:"Name"`
	XssMatchTuples interface{} `yaml:"XssMatchTuples,omitempty"`
}

// NewWAFRegionalXssMatchSet constructor creates a new WAFRegionalXssMatchSet
func NewWAFRegionalXssMatchSet(properties WAFRegionalXssMatchSetProperties, deps ...interface{}) WAFRegionalXssMatchSet {
	return WAFRegionalXssMatchSet{
		Type:       "AWS::WAFRegional::XssMatchSet",
		Properties: properties,
		DependsOn:  deps,
	}
}

// ParseWAFRegionalXssMatchSet parses WAFRegionalXssMatchSet
func ParseWAFRegionalXssMatchSet(
	name string,
	data string,
) (
	source string,
	conditions types.TemplateObject,
	metadata types.TemplateObject,
	mappings types.TemplateObject,
	outputs types.TemplateObject,
	parameters types.TemplateObject,
	resources types.TemplateObject,
	transform types.TemplateObject,
	errors []error,
) {
	source = "kombustion-core-resources"
	var resource WAFRegionalXssMatchSet
	err := yaml.Unmarshal([]byte(data), &resource)

	if err != nil {
		errors = append(errors, err)
		return
	}

	if validateErrs := resource.Properties.Validate(); len(errors) > 0 {
		errors = append(errors, validateErrs...)
		return
	}

	resources = types.TemplateObject{name: resource}

	return
}

// ParseWAFRegionalXssMatchSet validator
func (resource WAFRegionalXssMatchSet) Validate() []error {
	return resource.Properties.Validate()
}

// ParseWAFRegionalXssMatchSetProperties validator
func (resource WAFRegionalXssMatchSetProperties) Validate() []error {
	errors := []error{}
	if resource.Name == nil {
		errors = append(errors, fmt.Errorf("Missing required field 'Name'"))
	}
	return errors
}
